### ISSUE TITLE
Sauvegarder une requête (JSON ou SPARQL), et réinitialiser le composant depuis cette requête

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#101]
Pour sauvegarder des requêtes et founir des accès directs à des requêtes pré-paramétrées via des URLs

**Comment by antoine37120** [comment]
Pour memo, un code pour encoder du json dans une url :
```js
url = Object.keys(data).map(function(k) {
    return encodeURIComponent(k) + '=' + encodeURIComponent(data[k])
}).join('&')
```
Reste à étudier combien de caractères cela génère. Il est conseillé de ne pas dépasser les 2000.
A étudier aussi l'impact de d'autres issues, comme l’utilisation de différentes bases de données ou mode simple ou expert...

**Comment by tfrancart** [comment]
(Enregistrer directement dans l'interface ? cookie ? localStorage du navigateur (https://developer.mozilla.org/fr/docs/Web/API/Window/localStorage) ?)

**Comment by tfrancart** [comment]
Spécifications de plusieurs formes de requêtes SPARQL générées dans tous les patterns possibles:


## 1 critère sans choix de valeur (avec critère de liste)

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Museum>;
    <http://dbpedia.org/ontology/country> ?Country1.
  ?Country1 rdf:type <http://dbpedia.org/ontology/Country>.
}
```

## 1 critère avec une valeur dans une liste

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Museum>;
    <http://dbpedia.org/ontology/country> <http://fr.dbpedia.org/resource/France>.
}
```

## 1 critère avec plusieurs valeurs sélectionnées (dans une liste)

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Museum>;
    <http://dbpedia.org/ontology/country> ?Country1.
  VALUES ?Country1 {
    <http://fr.dbpedia.org/resource/France>
    <http://fr.dbpedia.org/resource/Suisse>
  }
}
```


## 1 critère avec un autocomplete

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Artwork>;
    <http://dbpedia.org/ontology/author> <http://fr.dbpedia.org/resource/Pablo_Picasso>.
}
```

## 1 critère avec une date de début seulement

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Person>;
    <http://dbpedia.org/ontology/birthDate> ?Date1.
  FILTER((xsd:dateTime(?Date1)) >= "1896-07-29"^^xsd:dateTime)
}
```

## 1 critère avec une date de fin seulement

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Person>;
    <http://dbpedia.org/ontology/birthDate> ?Date1.
  FILTER((xsd:dateTime(?Date1)) <= "1906-07-29"^^xsd:dateTime)
}
```

## 1 critère avec une date de début et de fin

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Person>;
    <http://dbpedia.org/ontology/birthDate> ?Date1.
  FILTER(((xsd:dateTime(?Date1)) >= "1886-07-29"^^xsd:dateTime) && ((xsd:dateTime(?Date1)) <= "1908-07-29"^^xsd:dateTime))
}
```

## 1 critère avec un "Search"

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT DISTINCT (STR(?theLabel) AS ?label) ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Person>;
    <http://labs.sparna.fr/sparnatural-demo-dbpedia/onto#search> ?Search1.
  FILTER(REGEX(?Search1, "pablo", "i"))
}
```


## 2 critères avec un AND

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Person>;
    <http://dbpedia.org/ontology/movement> <http://fr.dbpedia.org/resource/Baroque>.
  ?this <http://dbpedia.org/ontology/birthPlace>/<http://dbpedia.org/ontology/country> <http://fr.dbpedia.org/resource/France>.
}
```

## 2 critères avec un WHERE

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Artwork>;
    <http://dbpedia.org/ontology/museum> ?Museum1.
  ?Museum1 rdf:type <http://dbpedia.org/ontology/Museum>.
  ?Museum1 <http://dbpedia.org/ontology/country> <http://fr.dbpedia.org/resource/France>.
}
```

## 2 critères avec un AND OPTIONAL

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Person>;
    <http://dbpedia.org/ontology/movement> <http://fr.dbpedia.org/resource/Baroque>.
  OPTIONAL {
  	?this <http://dbpedia.org/ontology/birthPlace>/<http://dbpedia.org/ontology/country> <http://fr.dbpedia.org/resource/France>.
  }
}
```

## 2 critères avec un WHERE OPTIONAL

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Artwork>;
    <http://dbpedia.org/ontology/museum> ?Museum1.
  ?Museum1 rdf:type <http://dbpedia.org/ontology/Museum>.
  OPTIONAL {
	  ?Museum1 <http://dbpedia.org/ontology/country> <http://fr.dbpedia.org/resource/France>.
  }
}
```

## Query complexe combinant AND / WHERE / valeurs multiples

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
SELECT DISTINCT ?this WHERE {
  ?this rdf:type <http://dbpedia.org/ontology/Museum>;
    <http://dbpedia.org/ontology/country> ?Country1.
  VALUES ?Country1 {
    <http://fr.dbpedia.org/resource/France>
    <http://fr.dbpedia.org/resource/États-Unis>
  }
  ?this ^<http://dbpedia.org/ontology/museum> ?Artwork2.
  ?Artwork2 rdf:type <http://dbpedia.org/ontology/Artwork>.
  ?Artwork2 <http://dbpedia.org/ontology/author> ?Person3.
  ?Person3 rdf:type <http://dbpedia.org/ontology/Person>.
  ?Person3 <http://dbpedia.org/ontology/movement> <http://fr.dbpedia.org/resource/Baroque>.
}
```

**Comment by tfrancart** [comment]
Code de génération des noms de variables actuel : https://github.com/sparna-git/Sparnatural/blob/master/src/QueryGenerators.js#L111
La génération des noms de variables devrait se faire en amont lors de la création de la structure de la requête. Et le QueryGenerator devrait lire les noms des variables générés

Les noms de variable peuvent être conservés dans CriteriaGroup (sparnatural.js ligne 541)

**Comment by tfrancart** [comment]
Code de parsing d'une requête SPARQL en JSON : https://github.com/sparna-git/Sparnatural/blob/3fe67398d670e2c270ff87101748ec3dce82df01/assets/js/main.js

**Comment by tfrancart** [comment]
Note : dans le cas où il y a une incohérence entre la config de Sparnatural et la requête à chargée (par exemple on doit sélectionner une classe mentionnée dans la requête mais qui n'est pas dans la liste de classes), alors:
  1. soit on considère que c'est une erreur et on ne charge pas la requête et on met un log sur la console
  2. soit on montre le critère quand même (en prenant par exemple l'URI comme libellé d'affichage) et on fait par exemple un fond hachuré - ce ne serait pas bloquant pour le chargement.

Thomas ajoutera 2 exemples de requête : 1 avec une classe qui n'existe pas, 1 avec une propriété qui n'existe pas.

**Comment by tfrancart** [comment]
Il y a un cas qui ne marchera pas : le cas où une propriété dans la config peut avoir pour range plusieurs classes. Comme on n'a pas le type des valeurs saisies dans le SPARQL, on ne saura pas quelle classes sélectionnée en range. On laisse ce cas de côté pour l'instant, on traitera après.

**Comment by tfrancart** [comment]
Hello @antoine37120 plus j'y pense, plus je pense que la sauvegarde/rechargement des requêtes directement à partir du SPARQL ne marchera pas. Il nous faut une structure JSON de query Sparnatural:
  1. Définir une structure JSON correspondant à la structure d'une requête Sparnatural (`Query`, `CriteriaGroup`, `CriteriaLine`, etc.)
  2. Générer la structure JSON en sortie de Sparnatural
  3. Au rechargement, recharger à partir de la structure JSON
  4. Eventuellement, être capable de convertir du SPARQL dans la structure JSON
  5. (Eventuellement, à la génération du SPARQL, passer par la génération du JSON intermédiaire pour produire le SPARQL final)

Je vais essayer de te proposer un début de structure JSON de données dans une branche dédiée.

**Comment by antoine37120** [comment]
@tfrancart,
Une nouvelle class est maintenant disponible pour générer et retrouver les noms de variable associées au sijets et objets.
Les noms de variables sont donc attribués au moment de la sélection des Class (event update startClass ou endClass) et non plus pendant la génération de la requête.

**Comment by antoine37120** [comment]
Le support est maintenant complet pour les noms de variables du sujet en prenant en compte les noms utilisé pour les objets parente ou les sujets frères de premier niveau.
Je laisse encore en commentaire des anciens morceaux de codes jusqu'à ce que des tests soient réalisés.

**Comment by antoine37120** [comment]
@tfrancart : Extraction du json de l'url en place, + présélection des class de la première ligne ok
A suivre l'itération sur l'arborescence.

Un lien de test est utilisable sous le code de la requête générée.

**Comment by antoine37120** [comment]
Effectivement, cela peut être déporté. Ca complexifiera peut être l'intégration de cette fonctionnalité pour la mettre en place dans la page.
Je continu comme cela pour cette phase de dev et puis nous verrons en dernier l'interfaçage de sparnatural avec un json en entré.
A noté que pour le moment, doit être considéré que le json à fournir devra l'être au moment d'instancier le composant dans la page.
