### ISSUE TITLE
Widget dates

### ISSUE THREAD

**Issue by antoine37120** [sparna-git/Sparnatural#11]

**Comment by tfrancart** [comment]
Format JSON attendu pour les dates :

```
[
	{
		"label" : "Antiquité Romaine",
		"synonyms" : ["Antiquité", "Toto"],
		"start" : {
			"year" : "-0050"
		},
		"stop" : {
			"year" : "0499"
		},
		"uri" : "http://toto.fr/p0qhb66xxxxx"
	},
	{
		...
	},
]
```

Dans le libellé d'affichage, on affichera le label avec les dates entres parenthèses : `Antiquité Romaine (-0050, 0499)`

**Comment by tfrancart** [comment]
Pour les dates, on télécharge toujours toute la liste et c'est easyautocomplete qui cherche les chaines.
(Note : bien chercher en même temps sur les champs "label" et "synonyms"
