### ISSUE TITLE
« Inside » : permettre d’inclure une requête déjà construite dans un critère englobant 

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#114]

**Comment by tfrancart** [comment]
Ability to move from this:

![image](https://user-images.githubusercontent.com/2728945/76217400-a5ded900-6212-11ea-95e0-27f432f08da8.png)

"Works created by a spanish painter"

To this:

![image](https://user-images.githubusercontent.com/2728945/76217362-952e6300-6212-11ea-82f0-c4811e4c4433.png)

"Museum that expose works created by a spanish painter"

**Comment by antoine37120** [comment]
Effectivement ceci pourrait ce concevoir en proposant d'ajouter un critère au dessus du premier et cela de manière récursive.
Sur le plan ergonomique, l'élément à cliquer ne peut pas être au dehors de la zone verte, il faudra le prévoir à gauche du critère.

**Comment by tfrancart** [comment]
- Problème des décalages à droite et en bas pour l'utilisateur
- Question du retour arrière : si on annule le critère ajouté avant de l'avoir terminé, il ne faut pas que ça supprime tout le critère en dessous mais que ca revienne à l'état initial

**Comment by tfrancart** [comment]
Now that we have default label properties + inverse paths, this is not needed anymore
