### ISSUE TITLE
Allow to change the selected property when there are multiple choices

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#128]
Problem : if some values have already been selected, it is possible that the newly selected property does not have the same widget type.
Solution : if user decides to change the property, delete all the values selected previously and return to this state of the component :

Before :

![image](https://user-images.githubusercontent.com/2728945/68460082-3d9dcd80-0207-11ea-8ee9-047d1ecfb7db.png)

And if I decide to change "Mort à", I should return to :

![image](https://user-images.githubusercontent.com/2728945/68460176-76d63d80-0207-11ea-9d0e-9ffc04b7801a.png)

Note that the widget shown when the property is deselected is still the widget of the previously selected property. Would be better to reset also this part.

**Comment by antoine37120** [comment]
En suivant ces conditions cela semble limiter les problèmes. Je m'en occupe mais peut-être pas dans la semaine. Je te tien au courant.

**Comment by antoine37120** [comment]
C'est en place. Possibilité de tester avec les relation Personne => Pays ou Date.
Si l'action Where est utilisée pour un sous critère la liste des propriétés reste modifiable. Ça marche bien !
Ceci est compatible avec la possibilité qu'un widget différent soit utilisé en fonction de la propriété sélectionnée (exemple avec les dates "né à" ou "mort à").

**Comment by tfrancart** [comment]
Si je comprends bien on ne peut pas changer la propriété si on a déjà sélectionné des valeurs. Ca me va !
