### ISSUE TITLE
Depuis les ajustements pour que la sélection de valeur reste visible, le "et" sous la classe est toujours visible. Il ne doit apparaitre qu'au survol

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#131]
@antoine37120 Comparer la copie d'écran ci-dessous, qui est l'affichage actuel, avec la copie d'écran en ligne à http://blog.sparna.fr/2019/06/13/sparnatural-ecrire-des-requetes-sparql-tout-naturellement/. On voit que les "Et" sont toujours visibles. Ils ne doivent apparaitre qu'au survol.

![image](https://user-images.githubusercontent.com/2728945/68672070-20dbff80-0551-11ea-8f11-397c1ac0b76f.png)

**Comment by tfrancart** [comment]
C'est mieux mais il y a un comportement un peu bizarre quand même... Si on a une recherche a plusieurs niveaux comme "Musée expose Oeuvre WHERE Oeuvre auteur Personne WHERE Personne né à Pays", et qu'on passe la souris de haut en bas sur les 3 lignes, les "ET" restent affichés, ils ne disparaissent pas.
Ce n'est pas facile à expliquer, il faudrait que je te montre !

**Comment by antoine37120** [comment]
Ok, une simple suppression général de la class css appliquant la règle d'affichage de l'action à permis de résoudre ce comportement blizzard avant qu'elle soit appliqué au critère effectivement survolé.

**Comment by tfrancart** [comment]
OK
