### ISSUE TITLE
Remove the dependency on FontAwesome fa-times-circle

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#141]
EndClassGroup (and others) :

```
this.unselect = $('<span class="unselect unselectEndClass"><i class="far fa-times-circle"></i></span>') ;
```

The image should instead be packaged with the source

**Comment by antoine37120** [comment]
@tfrancart You can check this

**Comment by tfrancart** [comment]
Je suis chiant mais c'est moins joli qu'avant car 1/ la croix est plus grosse et 2/ il n'y a plus le léger liseré blanc qui entoure le rond - tu aurais moyen de faire quelque chose pour ça ?

![image](https://user-images.githubusercontent.com/2728945/133678861-decc2217-119a-4ce2-99d6-bc8c2335d0ec.png)

**Comment by tfrancart** [comment]
@antoine37120 je crois qu'on n'avait pas été au bout de cette issue...

**Comment by tfrancart** [comment]
In V8 we still have this in the tree widget
