### ISSUE TITLE
Are the "config" folders mentioned in README.md missing?

### ISSUE THREAD

**Issue by jakubklimek** [sparna-git/Sparnatural#150]
I was trying to make Sparnatural run on my own SPARQL endpoint. In README.md, you mention config folders in individual demos, but I can't find them. The config JSON-LDs are included only in index.html and then apparently they are used in the compiled sparnatural.js, but it is not clear where they are in their source form (to be adjusted).

**Comment by tfrancart** [comment]
You are right, the config is now directly included in the HTML page of each demo.
I suggest you copy one of the demo page and adapt the config to suit your needs, this is the easiest.
Try with the most recent one : https://github.com/sparna-git/Sparnatural/tree/master/sparnatural-demo-an.
I will adjust the README file.

**Comment by tfrancart** [comment]
Note that it is still possible to provide the config as a separate file. See source code at https://github.com/sparna-git/Sparnatural/blob/master/src/SpecificationProviderFactory.js
This part is currently rewritten to provide RDF-based configuration.

**Comment by tfrancart** [comment]
Could you close the issue if the update of the README is OK:

```
  3. Look at how the specifications are written by looking at the source of sparnatural-demo-dbpedia/index.html
  4. Adapt sparnatural-demo-dbpedia/index.html by changing the configuration and adapting the SPARQL endpoint URL;
```

Thanks
