### ISSUE TITLE
Cannot run in npm

### ISSUE THREAD

**Issue by jakubklimek** [sparna-git/Sparnatural#151]
I tried running Sparnatural using `npm run start` as described in https://github.com/sparna-git/Sparnatural/wiki/Developing-and-Compiling.
1. You are missing the `npm i` step there
2. `npm run start` fails anyway:
```
> Sparnatural@3.0.0 start /mnt/c/Users/Kuba/Documents/GitHub/Sparnatural
> webpack-dev-server -d --hot --config webpack.config.js --watch

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /mnt/c/Users/Kuba/Documents/GitHub/Sparnatural/dist
ℹ ｢wds｣: 404s will fallback to /index.html
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn cmd.exe',
  path: 'cmd.exe',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:8080/' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Sparnatural@3.0.0 start: `webpack-dev-server -d --hot --config webpack.config.js --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Sparnatural@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/klimek/.npm/_logs/2020-04-16T06_13_06_248Z-debug.log
```

**Comment by tfrancart** [comment]
No clue what this means.
1. Does the modified wiki page at https://github.com/sparna-git/Sparnatural/wiki/Developing-and-Compiling looks correct to you ? it not, can you edit it directly ?
2. Does the solution documented at https://peterthaleikis.com/posts/how-to-fix-throw-er-unhandled-error-event.html solves your issue ?

**Comment by jakubklimek** [comment]
1. you have a typo there now "nom" => "npm" and I cannot edit it as I am not a collaborator
Actually, this happened when npm I was run in "Bash on Ubuntu on Windows" environment. Not sure why it calls "cmd.exe", which of course does not make sense.
When I cleared node_modules and reinstalled (npm i) in Windows command line, it works.

Have you tried running this in Linux environment?

**Comment by tfrancart** [comment]
Typo fixed.
I do work and develop on Ubuntu myself.
Please close the issue if you consider it fixed.
Thanks !
