### ISSUE TITLE
Dynamic configuration : disable/remove types and links if not available in the data

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#167]
Given :

1. a configuration
2. a SPARQL endpoint queried by Sparnatural

Remove from the types and links shown to the user items without any actual instances in the data.

The SPARQL endpoint should be queried dynamically to test if each domain and range of each property actually exists in the data. If they are not present, the component should behave as the corresponding domain or range does not exist in the config.

The tests should be done asynchronously and should not block the loading of the component in the page.

This is useful to have a single generic config that adapts to multiple datasources that do not have the same granularity or that do not implement all of the data model.

**Comment by antoine37120** [comment]
First, add promise for waiting this check before displaying the UI.

**Comment by antoine37120** [comment]
We have 2 strategy to save the requests reponse and not send query to serveur endpoint : 
- Using localStorage, no lifetime expiration but we can add it. https://developer.mozilla.org/fr/docs/Web/API/Window/localStorage
- Using sessionStorage, data is clear when navigator tabs or windows is closed. But when open new tabs or windows, the data  will be reloaded. https://developer.mozilla.org/fr/docs/Web/API/Window/sessionStorage

Support for this functions is now great.

**Comment by antoine37120** [comment]
If we want to exclude jQuery, the ajax can be supported by javascript APi Fetch : https://developer.mozilla.org/fr/docs/Web/API/Fetch_API/Using_Fetch

We can include polyfile for olds borwsers : https://github.com/github/fetch

fetch() is successor of XMLHttpRequest, and have somme functions and options same as $ajax of jQuery.

Exemple : 
```js
var myHeaders = new Headers();

var myInit = { method: 'GET',
               headers: myHeaders,
               mode: 'cors',
               cache: 'default' };

var myRequest = new Request('flowers.jpg',myInit);

fetch(myRequest,myInit)
.then(function(response) {
  return response.blob();
})
.then(function(myBlob) {
  var objectURL = URL.createObjectURL(myBlob);
  myImage.src = objectURL;
});
```
The request response can be Blob, json, text, form data...

**Comment by tfrancart** [comment]
Messages in console:

![image](https://user-images.githubusercontent.com/2728945/132537758-3872063c-7276-4a84-94ba-7a556368c74a.png)

**Comment by tfrancart** [comment]
https://caniuse.com/fetch

**Comment by antoine37120** [comment]
Setting for statistics enencement is checked.

**Comment by antoine37120** [comment]
@tfrancart  For caching, the fetch api do not have feature for use TTL. Options are just strategics and use the server request header info for expiration delay.
Would you want we implement a new Class for caching data with sessionStorage or localStorage ?
This Class can be generic for any data caching on Sparnatural.
We can creat a fonction wrapper for fetch "fetchCached" with same parameter and add 1 more for TLL.
```js
fetchCached(url, Init, ttl) {
getLast loading date in sessionStorarage // use url for data key in storage
if (last loading date < now - ttl ) {
    reload with fetch ("reload" option value for cache)
    setLastLoading date to now ;
} else {
    load with fetch ("force-cache" option value for cache)
}

So, we dont save the request data on storage but just the date of last request reloaded.
And data is stored by browser caching.
I dont know if local (or sessions) storage is more efficient than browser storage for read data.

**Comment by antoine37120** [comment]
TTL can be set in settings for statistics.

**Comment by antoine37120** [comment]
And I think localStorage is a best choice with this.
