### ISSUE TITLE
Dans la saisie d'un critère, afficher un libellé par défaut dans la propriété lorsqu'on est en train de choisir la classe cible

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#173]
cf le comportenent de ResearchSpace qui affiche "related to" quand on construit un critère de recherche :

![image](https://user-images.githubusercontent.com/2728945/82840769-0b6a6980-9ed4-11ea-9643-78877b7eb91c.png)

**Comment by tfrancart** [comment]
Voilà ce qu'on a à présent : (pas de libellé entre les 2 classes en cours de sélection)

![image](https://user-images.githubusercontent.com/2728945/130514044-db7de703-ea44-41da-a8a0-b69a1418b164.png)

**Comment by tfrancart** [comment]
En anglais : "... related to"
En français : "... relié(e) à"

A mettre dans les fichiers de langues

**Comment by antoine37120** [comment]
@tfrancart You can check this
