### ISSUE TITLE
Missing the index-semapps.html from the  VCS

### ISSUE THREAD

**Issue by Murloc6** [sparna-git/Sparnatural#189]
First of all thank you very much for your share. This project is a really nice one!

I tried to deploy it locally, and I am interesting  by the "semapps" example since it used a .ttl file to define the Sparnatural configuration.
Unfortunately the index-semapps.html is missing from the VCS. When I tried a `npm run start` I obtained the following error:

```
Child html-webpack-plugin for "index-semapps.html":
    
    ERROR in Entry module not found: Error: Can't resolve '/home/murloc/Projects/RCF/Sparnatural/src/index-semapps.html' in '/home/murloc/Projects/RCF/Sparnatural'
```

Anything is fine for the others examples.

**Comment by tfrancart** [comment]
If you are interested in ttl configuration for Semapps looks under the demo/sparnatural-demo-semapps folder.
Warning : ontology-based configuration is Work In Progress, and not stable

You are correct that there is an inconsistency in the weback descriptor, but I think index-semapps should be removed from webpack.config.js

**Comment by tfrancart** [comment]
Just removed index-semapps.html from webpack.config.js
Let me know if it solves your problem

**Comment by Murloc6** [comment]
It has fixed the problem for the build :) And I use html from demo/sparnatural-demo-semapps as an example.

Thank you for the answer. I close this issue :)

Fixed by https://github.com/sparna-git/Sparnatural/commit/23c721918990df6bd7b5221e82ae3786b4f897e2

**Comment by tfrancart** [comment]
Cool. I am available for help if needed.
