### ISSUE TITLE
date filters don't work on xsd:dateTime litterals

### ISSUE THREAD

**Issue by semanticfire** [sparna-git/Sparnatural#190]
If you have a xsd:dateTime as range and you want to filter that with the sparnatural:TimeProperty-Date widget you will not get results.

The query contains `?dateTime1 <= "2021-01-19"^^xsd:date` which fails since the ?dateTime1 is of datatype xsd:dateTime.

This can be solved by wrapping the index in a casting function call, I'll submit a PR later this week.
the result will be `(xsd:date(?dateTime1)) <= "2021-01-19"^^xsd:date` which works as expected

**Comment by tfrancart** [comment]
Thanks - For the record SPARQL does not define the comparison operator for xsd:date, only for xsd:dateTime : https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#OperatorMapping

So maybe a better modification would be to generate a SPARQL query using an xsd:dateTime value, and still cast the compared variable to xsd:dateTime

**Comment by semanticfire** [comment]
That is true as well, I'll try what happens when I change everything to date time, considering, it will not be a date time.

**Comment by semanticfire** [comment]
> That is true as well, I'll try what happens when I change everything to date time, considering, it will not be a date time.

It works flawlessly on Stardog, we probably need to test on other stores
