### ISSUE TITLE
Default behavior when no result to populate dropdown box

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#195]
When a dropdown is filled by a SPARQL query, and there are no results, a clean behavior should be proposed instead of showing "undefined" in the dropdown:

![image](https://user-images.githubusercontent.com/2728945/108702540-b19ddb00-7509-11eb-9dcb-97d872989f45.png)

**Comment by tfrancart** [comment]
Remarque : émettre un log dans la console quand il n'y a aucun résultat pour une liste

**Comment by tfrancart** [comment]
A côté du label "Trouver Personne", afficher "Aucune valeur disponible" à la place de la liste.

**Comment by antoine37120** [comment]
@tfrancart You can check it.
You can change condition L:121 on widgets.js to view change if no item list with no result on demo.
