### ISSUE TITLE
Widget de list avec autocomplete

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#202]
Une dropdown list avec possibilité de filtrage des valeurs par un autocomplete.
Utile sur des listes longues - permet de voir l'intégralité des valeurs, éventuellement de les trier par occurrence

**Comment by tfrancart** [comment]
https://select2.org/getting-started/basic-usage

![image](https://user-images.githubusercontent.com/2728945/130516974-93421c53-9af2-4f82-903e-14b53ca9265a.png)

A la réflexion cela introduit une autre dépendance vers JQuery, ce qui n'est peut-être pas terrible

**Comment by tfrancart** [comment]
ping @antoine37120

**Comment by tfrancart** [comment]
@antoine37120 J'ai réussi à intégrer select2 dans la branche issue-202. Ca marche mais il faudrait styler le composant comme avec nice-select:

![image](https://user-images.githubusercontent.com/2728945/157911985-671c47f6-31ce-4081-a7ea-ef04f8ef910d.png)

- mettre le highlight en orange
- diminuer la taille de la police
- ...

Peux-tu jeter un oeil STP ? Il faut conserver la CSS existante pour le nice-select qui va continuer d'être utilisé.
Merci

**Comment by antoine37120** [comment]
@tfrancart c'est bon !
