### ISSUE TITLE
Ajouter un "waiter" pour les recherches avec autocompletion

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#215]

**Comment by tfrancart** [comment]
Dès qu'on a tapé 3 caractères

**Comment by tfrancart** [comment]
ping @antoine37120

**Comment by antoine37120** [comment]
@tfrancart tu peux réaliser un premier test sur la branche issue-215.
Donc au moins 3 lettre pour lancer la requête.
600ms avant de déclencher une requête lorsque l'on tape du texte.
Au bout de 30s il est considéré que la requête est foireuse (on peu enlever, augmenter ou reduir)
Les message s'affiche quand :
- Pas assez de lettres tapées
- En attente de la réponse
- Si pas de résultats retournés

**Comment by antoine37120** [comment]
@thomas,
Les traduction sont en place.
J'ai ajouté le fait de caché le message aucun résultat au focus out du champ pour éviter que cela reste afficher en permanence.
Et aussi, l'ajout du fait de supprimer le message quand le loader est réaffiché.
Tous les autres messages ont été supprimés. 
Veux tu que l'on ajoute quand même un texte du type "Recherche..." à coté du loader.

**Comment by tfrancart** [comment]
Top, merci pour tout ça. Le seul commentaire que j'ai c'est que la bande blanche avec le waiter ou le message "Pas de résultat" n'est pas tout à fait de la même largeur que le champ de recherche au-dessus ou que la liste des résultats d'autocompletion, peux-tu la mettre de la même largeur ?
Merci
