### ISSUE TITLE
Chargement des requêtes : la liste des properties reste ouverte

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#231]
1. Aller à http://sparnatural.eu/demos/demo-smt-cim10/
1. Charger la requête d'exemple "Maladies ayant pour cause une infection virale du système nerveux central" avec la dropdown

--> La liste des properties reste ouverte, alors qu'elle devrait se fermer :

![image](https://user-images.githubusercontent.com/2728945/140307727-b28ac64e-e3b7-4dd3-ae02-749f2aebc52b.png)

Peux-tu regarder ? Merci

**Comment by antoine37120** [comment]
J'ai tenté de retrouvé pourquoi elle s'ouvre alors qu'une donnée doit être chargée. Sans succée.
Un click simulé est pour le moment mis en place pour s'assuré qu'elle se ferme si se n'ai pas déjà fait.

**Comment by tfrancart** [comment]
Ca n'a pas réglé le souci. J'ai le même comportement qu'avant, et en plus maintenant, la dropdown des propriétés se colore en orange :
![image](https://user-images.githubusercontent.com/2728945/140976511-2545d066-46e2-4e47-b1d0-081670defd77.png)

**Comment by antoine37120** [comment]
@tfrancart j'ai trouvé pourquoi, il restait des sélecteurs suffisamment imprécis pour que dans le cas du chargement d'une requête, des clicks soient générés sur les mauvaises listes...
