### ISSUE TITLE
Add more columns to the sparql result

### ISSUE THREAD

**Issue by asicilia** [sparna-git/Sparnatural#240]
Hi,
It could be interesting to add a new feature to include more columns to the sparql output based on the main class selected. For example, right now when you select a Museum its label and IRI are displayed in the table, however it would be great to display also other datatype properties from Museum class such as "openingDate". 
The idea, is to setup which datatype properties for each Class should be included in the SELECT clause and displayed in the table in the configuration file.

**Comment by tfrancart** [comment]
We are actually currently addressing this as an evolution, with the ability for the user to select which column he wants. Stay tuned !

**Comment by tfrancart** [comment]
Hi @asicilia The latest release includes the ability for the user to select which column to include in the result set. Check out the demo at http://sparnatural.eu/demos/demo-dbpedia-v2/ and use the "eyes" to select which columns to include.
With your permission I close this issue, reopen it or open a new one if you have questions related to this. Thanks
