### ISSUE TITLE
Change color behavior when selecting values

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#242]
When selecting values using a list or autocomplete field, it is the values that are currently highlighted in orange.
It should now be the _target class_ that is highlighted in orange, and the values themselves should be highlighted in a different color.
Then the target class in orange can be selected as a column in the result.

**Comment by antoine37120** [comment]
@tfrancart Cela est maintenant fait dans le dernier commit réalisé ci-dessus
