### ISSUE TITLE
Add button to execute query directly from Sparnatural

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#243]
With proper handler to pass a function as parameter that will be executed.
function : "onSubmit".
If nothing is provided for "onSubmit", the button will not be displayed.

**Comment by tfrancart** [comment]
We need another function that will be called from the HTML page to notify Sparnatural when the query is finished, and when the submit is allowed

**Comment by antoine37120** [comment]
Maquette : 
![image](https://user-images.githubusercontent.com/464395/153951978-fe434859-7da0-4e39-9792-e9d251d0b750.png)

**Comment by antoine37120** [comment]
@thomas, c'est prêt à tester, je crois qu'il y a tous ce que tu souhaitais : 
Voir les petits ajouts dans index.html avec #243 en commentaire là ou il y a des modifs
Donc il y a la fonction onSubmit qui s'ajoute aux settings du composant. Par défaut, si on ne veut pas du bouton celle-ci doit rester une simple variable ne contenant pas de fonction.
Il y a 2 fonctions ```sparnatural.enableLoading()``` et ```sparnatural.disableLoading()``` pour activer et désactiver l'affichage du loader depuis un autre endroit que dans le composant.
Il y a aussi 2 autres fonctions ```sparnatural.enableSubmit()``` et ```sparnatural.disableSubmit()``` qui peuvent être utilisées pour bloquer ou débloquer l'usage du bouton de soumission de la requête.
Il y a donc bien maintenant un status désactivé pour le bouton. Il se débloque automatiquement juste après avoir exécuté ```onQueryUpdated``` avec la fonction ```sparnatural.enableSubmit()```.

Testé en désactivant la définition de la fonction dans index.html. La ligne 559 doit être décommentée pour ce test.

**Comment by antoine37120** [comment]
@tfrancart tu peux ajouter ceci après la ligne 621 dans index.html : 
``js
$([document.documentElement, document.body]).animate({
            scrollTop: $("#yasr").offset().top
        }, 1000);
```
Cela permet de scroller automatiquement vers les résultats une fois qu'ils sont reçus. A toi de voir si c'est sympas.

**Comment by antoine37120** [comment]
j'ai la sensation que les proportions du bouton sont plus petites que vis à vis de la maquette ?

**Comment by antoine37120** [comment]
J'ai revue les proportions des éléments afin qu'ils correspondent mieux à celles de la maquette.

**Comment by tfrancart** [comment]
Mergée et fermée (j'ai fait une micro-modification sur la CSS du bouton en particulier pour enlever le border)
