### ISSUE TITLE
Add a "Reset" button to clear the interface

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#244]

**Comment by antoine37120** [comment]
I have looking if is possible to add element on first criteria element but this is not compatible whith any funtion when Where clause is added.

I can add the button on the top of component before ul.componentsListe with wrapper to align this on the right and with 0 height. The button positionned on absolute can be on overflow of wrapper.

And I can add css rule for the first criteria with width calculated on css : calc(100% - button space in pixels) 
Button width : 54 px
Margin betwen criteria and button 20px

**Comment by tfrancart** [comment]
Je crois que je comprends :-) l'important est que ce soit aligné avec le bouton "play" d'exécution de la query
Tu peux commenter en français si c'est plus facile

**Comment by antoine37120** [comment]
@tfrancart ceci peut être testé

**Comment by tfrancart** [comment]
J'ai l'impression qu'un clic sur le bouton fait un reload complet de la page. Je vois toute la page qui se recharge et tous les javascript qui se rechargent dans la console. J'ai testé sous Firefox et Chrome et je constate la même chose.

**Comment by antoine37120** [comment]
Je viens de comprendre que si l'attribut href est défini et même si la sa valeur est vide dans une balise a, le navigateur continu le processus enclenché si on clique sur l'élément. Je corrige cela au plus tôt. Normalement le javavascript se charge déjà de réinitialiser le composant.

**Comment by antoine37120** [comment]
Tu peux aussi voir #266

**Comment by tfrancart** [comment]
merged and closed.
