### ISSUE TITLE
Onboarding tutorial using intro.js or sheperd

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#257]
The best choices seem to bee introjs : https://introjs.com/ (free for open-source, no dependencies) or sheperdjs : https://shepherdjs.dev/

**Comment by antoine37120** [comment]
@tfrancart 
Pour un premier test et imaginer l'intégration de Sheperdjs, j'ai commencé par essayer de l'utiliser pour voir ce que cela donne.
Tu peux jeter un œil en chargeant la branche issue-257. 
Tu auras certainement à faire npm instal pour ajouter sheperdjs.
Dis moi dans un premier temps si c'est bien ce type de scénario que l'on doit pouvoir mettre en place.

Ensuite, je me pose surtout la question de comment tu souhaite que chacun puisse mettre en œuvre son scénario pour le tuto.
Nous allons bien sûr mette sa configuration par défaut dans un fichier indépendant qui pourra être personnalisée.
Il sera peut être judicieux de prévoir que ce fichier puisse être chargé à part via la config du composant.

Ensuite pour décrire les étapes, cela resterai sous la forme que propose de le faire la librairie ? Du genre :  
```js
tour.addStep({
	id: 'step-home',
	text: 'Bienvenu dans le tutorial de Sparnatural',
	classes: 'example-step-extra-class',
	buttons: [
		{
			text: 'Non, merci',
			action: tour.cancel
		},
		{
			text: 'Suivre le tutoriel',
			action: tour.next
		}
	]
});
tour.addStep({
	id: 'step-0',
	text: 'L\'élément ci-dessus permet de rédiger votre premier critère de recherche',
	attachTo: {
		element: '#CriteriaGroup-0',
		on: 'bottom'
	},
	classes: 'example-step-extra-class',
	buttons: [
		{
			text: 'Next',
			action: tour.next
		}
	]
});
...
```

En essayant ce petit scénario, j'ai pu trouver une solution assez simple pour les cas ou une réaction du composant doit être attendu avant de passer à l'étape suivante. La stratégie est simplement de dire d'attendre quelques dixièmes de seconde.
Je pense en tout cas que cela peu suffire au risque qu'une autre méthode peut être plus propre soit moins accessible à mettre en place.

Voici un exemple de ce que cela donne avec un simple temps d'attente avant affichage de l'étape : 
```js
tour.addStep({
	id: 'step-5',
	text: 'La troisième étape est de choisir le type de relation entr le pays et la personne dans cette liste.',
	attachTo: {
		element: '#CriteriaGroup-0>.ObjectPropertyGroup ul.list',
		on: 'bottom'
	},
	classes: 'example-step-extra-class',
	buttons: [
		{
			text: 'Next...',
			action: tour.next
		}
	],
	beforeShowPromise: function() {
		return new Promise(function(resolve) {
			setTimeout( function () {
				resolve();
			}, 300);
		});
	}
});
```

Concrètement que veux tu que je te rendes compte pour cette étude d'intégration ?

**Comment by tfrancart** [comment]
> Dis moi dans un premier temps si c'est bien ce type de scénario que l'on doit pouvoir mettre en place.

Oui c'est ça. Il faudrait aller jusqu'à la création d'un premier critère complet, avec choix d'une valeur dans un widget de liste, et exécution de la query. Pourras-tu valider qu'on arrive à aller au bout ?

> Ensuite, je me pose surtout la question de comment tu souhaite que chacun puisse mettre en œuvre son scénario pour le tuto.
> Nous allons bien sûr mette sa configuration par défaut dans un fichier indépendant qui pourra être personnalisée.

Oui, c'est parfait. On peut imaginer qu'on passe en paramètre de Sparnatural le chemin vers le fichier de configuration JSON, et si pas présent, pas de tutorial.

> Ensuite pour décrire les étapes, cela resterai sous la forme que propose de le faire la librairie ?

Oui, on ne va pas réinventer un autre format JSON.

> En essayant ce petit scénario, j'ai pu trouver une solution assez simple pour les cas ou une réaction du composant doit être attendu avant de passer à l'étape suivante. La stratégie est simplement de dire d'attendre quelques dixièmes de seconde.
> Je pense en tout cas que cela peu suffire au risque qu'une autre méthode peut être plus propre soit moins accessible à mettre en place.

Je ne suis pas sûr de bien comprendre.
Ce que je voudrais juste c'est éviter qu'on puisse "sortir" du tutorial, par exemple dans l'étape qui montre la première liste _("La première étape est de choisir le type d'objet que vous cherchez dans cette liste")_, on peut cliquer sur n'importe quelle classe, et alors ça fout le bordel. Quelles solutions a-t-on pour éviter cela ?
Ce serait sûrement possible que dans la même étape on dise _"La première étape est de choisir le type d'objet que vous cherchez dans cette liste. Choisissez Musée pour continuer"_ et qu'alors le tutorial passe à la suite seulement si on clique sur Musée, et pas sur autre chose.

**Comment by antoine37120** [comment]
@tfrancart Je viens de réussir à finir ce que nous avions dit pour cette issue.
Désolé pour le délais mais je me suis un peu embêté pour rendre ce tuto complètement indépendant et définit seulement dans le index.html.

Pour le moment cela fonctionne avec le CDN de SheperdJs.
A toi de me dire si cela te convient de cette façon.
Si oui, nous pouvons l'enlever des packages du projet.

Attention à bien garder les variable ```tour, StepToWait3``` définies au niveau globales.

Concernant, Le suivit des clicks avec Select2 dans le cadre du tuto, je n'ai pas trouvé d'autre moyen que de déclencher l'étape suivante quand la fonction ```onQueryUpdated()```` est exécutée. Comme la liste des pays, nécessite un temps de chargement, c'est plus complexe à surveiller.

J'espère que cela te conviendra comme cela.
Ayant passé plus d'une journée sur cette issue et vu l'objectif initial, je pense que c'est déjà super ;)

**Comment by tfrancart** [comment]
C'est génial et parfait. J'ai adapté et intégré dans cette page: http://sparnatural.eu/demos/demo-dbpedia-v2/#
Le tuto se lance au clic sur le lien au-dessus de Sparnatural.
