### ISSUE TITLE
Error when defining sparqlEndpointUrl

### ISSUE THREAD

**Issue by timathom** [sparna-git/Sparnatural#261]
Thanks for the great tool! I would like to take advantage of the feature that allows sending queries to a [different SPARQL endpoint](https://github.com/sparna-git/Sparnatural/wiki/JSON-based-configuration#specifying-the-sparql-service-of-a-datasource).

I've tried modifying one of the demo configs to add the `datasource` object as shown in the documentation. For example:

```
{
  "@id": "http://labs.sparna.fr/sparnatural-demo-dbpedia/onto#birthPlace",
  "@type": "ObjectProperty",
  "subPropertyOf": "sparnatural:AutocompleteProperty",
  "label": [
    {
      "@value": "birth place",
      "@language": "en"
    },
    {
      "@value": "lieu de naissance",
      "@language": "fr"
    }
  ],
  "domain": "http://dbpedia.org/ontology/Country",
  "range": "http://dbpedia.org/ontology/Person",
  "sparqlString": "^(<http://dbpedia.org/ontology/birthPlace>/<http://dbpedia.org/ontology/country>)",
  "datasource": {
    "queryTemplate": "datasources:search_rdfslabel_strstarts",
    "labelProperty": "http://www.w3.org/2000/01/rdf-schema#label",
    "sparqlEndpointUrl": "http://dbpedia.org/sparql"
  }
}
```

However, whenever I tried to use an autocomplete with this configuration, an error is thrown:

`Uncaught TypeError: this.sparqlTemplate is undefined`

Is this feature currently supported, or have I overlooked something? Thanks in advance!

**Comment by tfrancart** [comment]
This is still supported, but if can switch to OWL-based configuration this may be more future proof.
The value of queryTemplate in the documentation page was wrong.  The reference must point to a **query template** (query_search_label_strstarts) and not to a **datasource**, so the config should be:

```
  "datasource": {
    "queryTemplate" : "datasources:query_search_label_strstarts"
    "labelProperty": "http://www.w3.org/2000/01/rdf-schema#label",
    "sparqlEndpointUrl": "http://dbpedia.org/sparql"
  }
```

Note that you can override the entire SPARQL endpoint for all Sparnatural in a constructor parameter.

Please close the issue if fixed.

**Comment by timathom** [comment]
Ah, thanks! The documentation was correct, but I missed that nuance. It's working now.
