### ISSUE TITLE
Enable HTTPS for the homepage

### ISSUE THREAD

**Issue by bencomp** [sparna-git/Sparnatural#262]
To improve security, SEO and privacy for your website visitors, it would be great if you could enable HTTPS on the Sparnatural homepage.

**Comment by tfrancart** [comment]
Thanks, this should be done now : https://sparnatural.eu/
Please close the issue if you think it is correct.
Note that the site is hosted on Github Pages : https://github.com/sparna-git/sparnatural.eu

**Comment by tfrancart** [comment]
Rollback : I removed HTTPS. This causes issues with the demos when the SPARQL endpoint is HTTP only.

**Comment by tfrancart** [comment]
HTTPS is now generalized on the website and demo pages
