### ISSUE TITLE
Add ability to edit variables names

### ISSUE THREAD

**Issue by antoine37120** [sparna-git/Sparnatural#265]
Here original design of editable variable on variable selector liste : 
![image](https://user-images.githubusercontent.com/464395/153628817-c699a6d8-f96b-4035-a869-081da4989958.png)

**Comment by antoine37120** [comment]
We can use javascript ```HTMLElement.contentEditable``` suported by all browsers.
This can be enanced on any elements by add ```contenteditable``` attribute with true value on html tag.
Doc : https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/contentEditable

After this, here exemple of javascript for check change on elements edited : 
```js
//trigger change editable variable
			$('body').on('focus', '[contenteditable]', function() {
				const $this = $(this);
				$this.data('before', $this.html());
			}).on('focusout', '[contenteditable]', function() {
				const $this = $(this);
				if ($this.data('before') !== $this.html()) {
					$this.data('before', $this.html());
					$this.trigger('change');
					console.log($this.html()) ;
				}
			});
```

We can choice to validate variable name on focusout or we can add buttons for actions validate and cancel changes.

For validate variable name, we can restrict used caracteres on key down event to check if event.code is on white liste of code ([a-b] and "_"). If code is not finded in white liste, the event propagation is stopped and key code is note added to html text of variable name.

For user, we can add tootip displayed on focus to explain what are authorized characters.

On unfocus or on validate action, we can check if variable name is ok (not empty and containe only character authorised. Need to re check the name if user paste any value on the input. I can see if on paste we "normalise" the variable name.

**Comment by antoine37120** [comment]
This is the default design of editable tag on edit : 
![image](https://user-images.githubusercontent.com/464395/153628015-da371083-5ffe-4090-953e-13fa035ab211.png)

**Comment by antoine37120** [comment]
Ce dernier commit devrait être sur #266

**Comment by antoine37120** [comment]
@tfrancart Que penses tu du commentaire fait un peu plus haut ?

**Comment by tfrancart** [comment]
1. Oui il faut autoriser seulement certain caractères. Formellement ces caractères sont définis à https://www.w3.org/TR/sparql11-query/#rVARNAME. Je pense qu'on peut autoriser les ranges suivants:

[A-Z] | [a-z] | [#x00C0-#x00D6] | [#x00D8-#x00F6] | [#x00F8-#x02FF] | [#x0370-#x037D] | [#x037F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF] | '_'

Inutile de mettre un tooltip d'explications.

On peut faire cette vérification au moment de la frappe, mais inutile de faire une vérification au focusout ou à la validation. Si on fait un copier-coller d'une valeur qui vient d'ailleurs c'est tant pis, le SPARQL sera invalide mais ce n'est plus vraiment notre problème.

2. Il ne faut pas mettre de boutons de validation, on valide au focusout ou si on appuie sur Enter

**Comment by antoine37120** [comment]
@tfrancart Je crois que l'on va rencontrer une grosse difficulté quand on veut changer "?this". Ce nom de variable est utilisé à plusieurs endroits dans le code.

**Comment by antoine37120** [comment]
C'est peut être moins compliqué que je ne le crois. A surveiller.

**Comment by antoine37120** [comment]
@thomas, tu peux tester cela.
Pour les caractères autorisés, pour le moment ce sont ceux ci : [a-zA-Z0-9_]
L'idéale serait d'avoir directement la liste des caractères pour les autres. Je ne vois pas d'exemple de regex en javascript avec les ranges de valeurs hexadécimale.

**Comment by tfrancart** [comment]
C'est top, ca marche pour éditer le ?this et les autres noms de colonnes. Il faudrait simplement:
  - valider la saisie quand on fait Enter (là ca valide seulement au focusout)
  - essayer de faire le style d'entourage pointillé un peu plus comme si c'était un champ d'input, avec un peu de padding à droite et à gauche.

**Comment by antoine37120** [comment]
@tfrancart C'est ajouté.
Si le CSS te plait pour le champs, il resterait donc la question des caractères spéciaux.

**Comment by antoine37120** [comment]
Il y une solution avec cette librairie : https://github.com/mathiasbynens/regenerate

En code d'exemple : 
```js
regenerate()
     .addRange(0x0, 0x10FFFF)     // all Unicode code points
     .removeRange(0xD800, 0xDBFF) // minus high surrogates
     .removeRange(0xDC00, 0xDFFF) // minus low surrogates
     .toRegExp()
```

**Comment by tfrancart** [comment]
1. Il faut bloquer la possibilité que le champs soit vide. Sinon impossible de pouvoir le rééditer, et on a une variable vide
2. La même source que toi me dis qu'il est possible en ES6 d'exprimer des ranges de caractères Unicode en ES6 : https://mathiasbynens.be/notes/es6-unicode-regex

Un truc du style : 
```
const regex = /[💩-💫]/u; // Or, `/[\u{1F4A9}-\u{1F4AB}]/u`.
```

Ne te prends pas la tête si ca ne marche pas, je vois où est la regex et je pourrai modifier plus tard, pour une première version c'est très bien.

**Comment by antoine37120** [comment]
@tfrancart Ajout d'un traitement au focus out pour réassigner le nom de variable avant édition (focus) si valeur vide.

**Comment by antoine37120** [comment]
@tfrancart Un bug sous Firefox, merci de l'avoir repéré de suite. Il apparait que firefox ajoute tout seul un `<br>` si une balise avec l'attribut contenteditable est vide. Peut être est fait pour que l'élément soit toujours cliquable. En tout les cas, firefox enlève ce `<br>` dès qu'il y a à nouveau du contenu. C'est donc corrigé en extrayant que du texte de la balise et non du html pour faire le test.

**Comment by antoine37120** [comment]
@tfrancart Sûr d'avoir tout recharger, j'arrive pas à reproduire le bug maintenant. J'avais effectivement ce br qui apparaissait dans la requête avant correction.

**Comment by tfrancart** [comment]
C'est OK maintenant merci, mergé et fermée.
