### ISSUE TITLE
Externalize "theme" (colors) in separate CSS

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#273]
1. Externalise in separate CSS + import
2. Add proper comments on each color
3. Provide a distinct blue theme
4. See if the background colors could be part of the CSS rather than computed in the Javascript

**Comment by antoine37120** [comment]
To calculate background colors for each criteria area we can add an hiden html element with css background color to get and convert on RVB css rule color with js. 

On scss, all colors are not on variables, generaly white, black, and greys.
We can add more grey levels from white to black on variables and I'm think this can be done to have a complete hand for theming generation.

Actualy : 
```scss
/* Color of the criteria arrows (orange) */
$custom-red: rgb(250,136,3) ;
/* Color of the "unselect" buttons in criterias */
$custom-red-bold: rgb(182, 97, 0) ;
/* Color of a selected value in a criteria */
$custom-red-medium: rgb(255, 210, 157) ;
$custom-red-light: rgb(255, 231, 203) ;

/* Color of the options arrow (optional / negation) */
$custom-green: rgb(107,215,171) ;
/* Color of the options arrow when not selected */
$custom-green-light: rgb(151,227,196) ;

/* Color of the highlight of arrows */
$custom-green-bold: rgb(2,184,117) ;

$custom-silver-line: #8D8D8D;
$custom-silver: rgb(167,167,167) ;
$custom-silver-light: rgb(230, 230, 230) ;
$default-text-color: #666 ;
```
In option we can add any variables for lines styles (borders styles and widths) used to display links between criterias. Links colors are already customizable.

For sizing elements we have any options but I think we need more to cover all changes on this variables : 
```scss
$component-width: 1200px;
$component-max-width: 90%;
$height-components: 54px;
$height-components-under: 48px;
$height-components-hover: 35px;
$margin-component: 30px;
$margin-component-onEdit: 80px;
$margin-children-li: 75px;

$center-arrow-bd-width : 3px;
```

**Comment by tfrancart** [comment]
Done, see _themes.scss
Next step can be to provide 2 or 3 different color themes based on this
