### ISSUE TITLE
Quand on modified un nom de variable, le nouveau nom n'est pas répercuté sur tous les StartClassGroup nécessaire

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#274]
1. Je créé la requête Musée --> Pays where Pays lieu de naissance Personne = Picasso"
2. J'ajoute avec l'oeil la variable Pays
3. Je modifie le nom de la variable "Country_1" en "Pays"
4. Résultat : la requête SPARQL générée est fausse, il reste une variable "Country_1" qui vient du StartClassGroup du second critère.

Quand on modifie un nom de variable, ce nouveau nom doit se répercuter non seulement sur le EndClassGroup ou le StartClassGroup qui a l'oeil activé, mais il doit être répercuté sur tous les critères enfants (quand la flèche sélectionnée était un EndClassGroup) ou frères (quand la flèche sélectionnée était la première)

Peux-tu regarder stp @antoine37120 ? merci

**Comment by tfrancart** [comment]
@antoine37120 pourras-tu regarder ce bug ? merci

**Comment by antoine37120** [comment]
@tfrancart, Il me semble que c'est aussi maintenant ok apprès plusieurs tests.
Il y avait aussi un bug si plusieurs objets du même type étaient sélectionnés pour l'affichage. Le composant ne reconnaissait pas l'objet pour lequel on éditait le nom de variable.

**Comment by tfrancart** [comment]
Ca fonctionne pour les critères fils, mais pas pour les critère frères:
1. Ja saisis la requête "Musée Pays = France ET Musée expose Oeuvre (toutes)"
2. Je modifie la variable "this" pour la renommer en "toto"
3. Il reste un "this" dans la requête SPARQL qui correspond au StartClassGroup du 2ème critère :

![image](https://user-images.githubusercontent.com/2728945/161942555-12ca72f6-65f2-4490-90c5-b84f3e3db1e5.png)

**Comment by antoine37120** [comment]
@tfrancart il y avait effectivement un gros manque d'implémentation sur cette fonctionnalité.
J'en ai profité pour reprendre certain éléments du code de la partie concernée.

**Comment by tfrancart** [comment]
C'est bon pour moi, merci pour toutes tes corrections

**Comment by tfrancart** [comment]
Hello @antoine37120 , désolé mais je découvre un problème là-dessus, sans doute lié à la dernière modification:

- Je fais la requête "Musée -- pays --> Pays WHERE Pays -- lieu de naissance --> Personne = Picasso"




- Je sélectionne la variable "Personne"
- Je modifie le nom de la variable en "Person_xxx"
- La variable du StartClassGroup de ce critère est modifiée, alors que c'est seulement la variable du EndClassGroup qui devrait être modifiée

Copie d'écran :

![image](https://user-images.githubusercontent.com/2728945/163183724-e25e6a7b-a888-4cc0-8c85-2c787cdddaf2.png)

**Comment by antoine37120** [comment]
@tfrancart Tu peux aussi tester ceci sur la branche issue-312. Ceci surtout pour éviter un conflit avec la précédente correction.
