### ISSUE TITLE
Generate SPARQL query on a date range, with a begin and an end predicate

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#276]
```

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# documents datés entre 1575 et 1580, adaptation de la requête de la diapo 14 du CR du COPIL de janvier. 
# Fonctionne bien : 5767 résultats, avec les données inférées. Ramène bien les pièces d'archives dont la description
# donne une date précise, avec rico:date.
# Par ex. ramène http://data.archives-nationales.culture.gouv.fr/recordResource/041101-c1p6rdg3ho0b--1673zws4p6jej 
# (déclaration par Marie de Sainctyon, rico:date=1577-04-01). Ramène aussi des groupes de documents dont la 
# date de début est antérieure à 1575, 
# par ex. http://data.archives-nationales.culture.gouv.fr/recordResource/041645-c1p6weknuscr--1b2kkbfd92z6g (minutes, 1568-1578).

SELECT DISTINCT ?this ?intitule ?date WHERE {
    ?this a rico:RecordResource ; rico:title ?intitule.
 ?this rico:date ?date.
 
  FILTER(
    (?date < "1575-01-01"^^xsd:date && "1575-01-01"^^xsd:date < ?date)
    ||
    (?date < "1580-12-31"^^xsd:date && "1580-12-31"^^xsd:date < ?date)
    ||
    ("1575-01-01"^^xsd:date < ?date && ?date < "1580-12-31"^^xsd:date)
  )  
}
ORDER BY ?intitule
```

this requires to know the 2 predicates associated to the single property in Sparnatural

**Comment by tfrancart** [comment]
@florenceclavaud : d'une façon générale, dans Sparnatural, on ne peut pas s'appuyer ou supposer que la base qu'on interroge fais de l'inférence. Par ailleurs, la requête telle que présentée est un peu bizarre, car ces lignes de FILTERS sont nécessairement toujours fausses:

```
    (?date < "1575-01-01"^^xsd:date && "1575-01-01"^^xsd:date < ?date)
    ||
    (?date < "1580-12-31"^^xsd:date && "1580-12-31"^^xsd:date < ?date)
```

Je vais proposer une requête modifiée

**Comment by tfrancart** [comment]
Cette requête modifiée donne 5520 résultats. Je ne sais pas dire d'où vient la différent de nombre de résultats. Cette requête me semble plus précise et plus ré-adaptable à d'autres situations, qu'en penses-tu ?

```


PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?this ?intitule WHERE {
    ?this a rico:RecordResource ; rico:title ?intitule.
  {
    {
      # soit une date unique...
      ?this rico:date ?date.   
      FILTER("1575-01-01"^^xsd:date < ?date && ?date < "1580-12-31"^^xsd:date)
    }  
    UNION
    {
      # soit une plage de date
      ?this rico:beginningDate ?beginDate.
      ?this rico:endDate ?endDate.
     
      FILTER(
        # chevauchement de la borne inférieure
        (?beginDate < "1575-01-01"^^xsd:date && "1575-01-01"^^xsd:date < ?endDate)
        ||
        # ou chevauchement de la borne supérieure
        (?beginDate < "1580-12-31"^^xsd:date && "1580-12-31"^^xsd:date < ?endDate)
        ||
        # ou l'intervalle de la ressource est complètement contenu dans l'intervalle demandé
        ("1575-01-01"^^xsd:date < ?beginDate && ?endDate < "1580-12-31"^^xsd:date)
      )
    }
  }
}
ORDER BY ?intitule
```

**Comment by tfrancart** [comment]
Par ailleurs il faut voir comment gérer les intervalles ouverts (une ressource qui n'aurait qu'une beginDate, sans endDate - ce n'est peut-être pas possible dans le cas des archives, mais dans d'autres cas, si.

**Comment by florenceclavaud** [comment]
Oui ça marche, et  c'est très bien. Je me suis embrouillée dans la requête SPARQL que tu as copiée dans ton premier commentaire.
Pour ce qui est de la différence en nb de résultats, ça reste à creuser (elle vient peut-être de ce que que dans la première requête j'avais aussi demandé à ramener la date, ?this ?intitule ?date).

Il reste aussi à voir le cas de la recherche sur une date unique : je cherche les docts datant de l'année 1575, ou du mois de juin 1575, ou du 15 janvier 1575. Ces requêtes sont tout aussi utiles dans la recherche en archives. Elles correspondent en général à un unique rico:date dans nos données. Bien sûr les deux premières (sur une année ou un mois) peuvent être interprétées comme des requêtes sur une période, et du coup on peut peut-être les ramener au même cas que le cas traité dans ce ticket, en proposant la même interface de saisie. La 2e est différente : on veut vraiment uniquement les documents - pièces d'archives le plus souvent - ayant une date précise, au jour près. C'est très simple à écrire en SPARQL, par contre la saisie devrait pouvoir se faire autrement.
Qu'est-ce que tu en penses @tfrancart ?

**Comment by florenceclavaud** [comment]
Suite : le cas où des ressources n'ont qu'une date de début, ou une date de fin, existe aussi dans les archives. Notamment pour les agents (personnes ou organismes) qui existent aujourd'hui, ou les activités, les événements. Pour ces ressources on utilise rico:beginningDate, rico:endDate, ou des sous-propriétés (rico:creationDate, rico:birthDate). On peut même imaginer des RecordSet n'ayant pas de date de fin (ensembles documentaires en cours de production), même si ici aux AN le cas n'existe pas encore actuellement, à ma connaissance.

**Comment by tfrancart** [comment]
J'ai traité le cas des intervalles ouvert, mais pas ce cas-ci : si on recherche sur un intervalle ouvert (en donnant seulement la date de début), et que les resources ont aussi un intervalle ouvert (avec seulement une date de naissance et pas de date de décès, parce que inconnue ou pas encore advenue), alors nécessairement les deux intervalles se recouvrent tout le temps. J'ai donc préféré exclure ce cas et si on cherche avec seulement une date de début, alors seule les resources avec une date de fin explicite seront ramenées.
