### ISSUE TITLE
Question: overloading loadQuery() in sparnatural.js

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#288]
Hi,
First of all, really like Sparnatural. Most intuitive SPARQL query builder so far. In fact, I like it so much I would like to have it in my React.js UI. For that i'm currently doing a partial refactor of the single file src/sparnatural.js to a Typescript definition. In the code, I noticed the function loadQuery() three times. 
1. https://github.com/sparna-git/Sparnatural/blob/af388921a4b15963dc5564322cabce908604eb31/src/sparnatural.js#L297
2. https://github.com/sparna-git/Sparnatural/blob/af388921a4b15963dc5564322cabce908604eb31/src/sparnatural.js#L328
3. https://github.com/sparna-git/Sparnatural/blob/af388921a4b15963dc5564322cabce908604eb31/src/sparnatural.js#L641

I'm no js expert at all but it seems a bit confusing for me. Is this meant to be a classical function overlading? 
And it seems to be the case that loadQuery() is only used in index-saved-query.html. I'm not sure what the purpose of index-saved-query.html is? Is it some kind of template? So you either use index.html or index.saved-query.html with some prestored queries?
If index-saved-query.html is only optional, then i could get rid of the loadQuery() functions?

**Comment by tfrancart** [comment]
Hi !

Thanks for your interest in Sparnatural ! Simply put, yes it's the best knowledge graph explorer / SPARQL query builder :-)

It's great to hear you want to port it in Typescript. This is going to be a small challenge :-)
You will see that the code has now 4 or 5 years and has went through much re-engineering and has a lot of history behind it - and was written by someone experienced in JS but not in object-oriented programming.

`sparnatural.loadQuery()` is used to load/init queries directly from a JSON data structure. I just documented that for you at https://docs.sparnatural.eu/Query-JSON-format
This is used for example here : https://sparnatural.eu/demos/demo-dbpedia-v2/ to load a query from the example queries dropdown box.
In the Sparnatural code this is only used in index-saved-query.html which is our test page for this feature.
If you are looking for a page/demo template I suggest you start from the HTML page at https://sparnatural.eu/demos/demo-dbpedia-v2/ which is hosted in this repo : https://github.com/sparna-git/sparnatural.eu

Now coming to your question : yes this is confusing.
1. The first one `this.loadQuery` is the entry point, attached to the Sparnatural instanc
2. The second one `loadQuery` is global function, not attached to Sparnatural, it can have another name
3. The third one is the code tied to the variables selector at the bottom when a query is loaded. Honestly I don't know why this is using `this` here. I'll try to sort that out.

If you get rid of the loadQuery functions you will loose the ability to save/reload/share your queries.

Finally, I am sure you have noticed this, but as Sparnatural is LGPGL, so the derivation you make in Typescript needs to be shared under the same licence.

**Comment by SteinerPascal** [comment]
Hi, First of all thanks for the quick reply!
Yes it will definetely take some time. And as a first step I'm not going to port it totally to TS but i will create a "wrapper" around the js code. Meaning i will focus on porting the sparnatural.js file to make it simpler for a possible framework usage. 
Thanks for the documentation! Very much appreciated. I will see on how i can integrate load query in the new structure.

Regarding the license: Sure I'm very much aware of that which is perfect since I'm in favor for Open Source anyway.

**Comment by SteinerPascal** [comment]
I'm resolving this issue since it's been answered
