### ISSUE TITLE
Searching through empty array in QueryGenerator

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#294]
Hi
It's me again. I have no started to port several classes from the sparnatural.js to independent TS classes. So far i think i haven't broken too many things. (Altough that's difficult to say without any UI or Unit tests). 
I noticed an odd line:
https://github.com/sparna-git/Sparnatural/blob/69e0b40d91332fd3079e092c20a1d05bf9b121c1/src/QueryGenerators.js#L161
it seems that the second Argument`this.WIDGETS_REQUIRING_VALUES` doesn't come from anywhere? Or am I missing something? 
So it basically is the same as searching through an empty Array like
`($.inArray(formObject.sparnatural.components[i].CriteriaGroup.EndClassWidgetGroup.inputTypeComponent.widgetType,[]) > -1)`

**Comment by tfrancart** [comment]
An obvious bug resulting from the porting of ancient code to a new structure.
I have commited a fix that adds the definition of that array in the constructor

**Comment by SteinerPascal** [comment]
Thanks!
