### ISSUE TITLE
If the query is currently being executed, and I modify smthg in Sparnatural, I can click again on "play" button to rerun the query

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#303]
This is dangerous as multiple queries can be sent at the same time.
The "Play" button should probably not turn green again is someothing changes in the query until previous query has finished.

**Comment by antoine37120** [comment]
@tfrancart,
Ceci a donc été dans ce commit qui est maintenant dans la branche Master
https://github.com/sparna-git/Sparnatural/commit/7b0f075c90bd47a1fd2b26ba4debfc0d1e0f8493
