### ISSUE TITLE
hidden <input> htmltags created in addComponent()

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#306]
I was wondering if these input types defined here have any usage(the one in the end with a- b- c-):
https://github.com/sparna-git/Sparnatural/blob/3202bc4b8e53f15b494c9d0f238886fa4d5cb2fc/src/sparnatural.js#L822

It doesn't seem like it?

**Comment by tfrancart** [comment]
Hi @SteinerPascal I have never replied to this one, but I think no, they don't have any usage;

**Comment by SteinerPascal** [comment]
That's alright. I left them out in the TS port anyway. Thanks for the answer!
