### ISSUE TITLE
Can SPAnatural do this type of query?

### ISSUE THREAD

**Issue by steve-at-siemens** [sparna-git/Sparnatural#309]
I don't know if this type of query is possible with SPAnatural...

```
SELECT ?concept ?entity
WHERE {
  ?concept rdfs:comment ?comment
  FILTER(REGEX(?comment, "keyword"))
  ?entity rdf:type ?concept
}
```
Basically, I'd like to query all the items that match a comment value but it seems the ?comment object value has to be a URI and not a variable?

Is this possible? What would I need to configure to make this work?

Many thanks,
Steve

**Comment by tfrancart** [comment]
Hello @steve-at-siemens I close the issue, feel free to reopen if you have further questions
