### ISSUE TITLE
It should not be possible to select variables with the "eye" inside a negative pattern

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#311]

**Comment by tfrancart** [comment]
Eye should be disabled in any negative criteria when the value is set to "All". If it has a value or a child in a Where clause, the eye should remain clickable

**Comment by antoine37120** [comment]
@tfrancart c'est bon, tu peux tester sur la branche issue-311.

**Comment by tfrancart** [comment]
@antoine37120 Merci, un petit ajustement est nécessaire:

Si on désactive l'oeil, il faut aussi enlever le contour vert:

![image](https://user-images.githubusercontent.com/2728945/174426340-3da0788e-3c72-4d06-b98a-f4a6282a6f32.png)

**Comment by antoine37120** [comment]
@tfrancart ceci vient d"être corrigé sur la branche issue-311
