### ISSUE TITLE
Adding an alert or dialog library 

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#313]
Hi have you guys ever thought about any kind of dialog library to interract with the user? 
For example to signal input validation or show connectivity errors?

Example: user inputs a data into the datewidget in which the startDate is bigger then the endDate. Dialog informs the user that this doesn't make sense. User (hopefully) enters a reasonable date selection.

something like this could be nice: https://github.com/marcelodolza/iziToast

**Comment by tfrancart** [comment]
See #369
