### ISSUE TITLE
TimeProperty in JSON based configuration? 

### ISSUE THREAD

**Issue by lubianat** [sparna-git/Sparnatural#314]
Hello! 

I  am exploring Sparnatural for some Wikidata-related applications. 

I am currently using JSON-based configuration, and I'd like to implement support for time properties (e.g. implement  a "publication date" property: https://www.wikidata.org/wiki/Property:P577) 

I am not very sure how to proceed in that case. Should I call it an `"@type" : "ObjectProperty"` too and assign it as a subproperty of sparnatural:TimeProperty-Date? 

I could not find it at the documentation (https://docs.sparnatural.eu/JSON-based-configuration), am I missing something? Do you have any tips on how to proceed? 

Thank you!

**Comment by tfrancart** [comment]
> Hello!

Hello and thanks for stopping by ! 

> I am exploring Sparnatural for some Wikidata-related applications.

Good to hear ! a while ago (actually at the very beginning of the project) I also tried that - with no luck, as the Wikidata SPARQL endpoint is not fast enough. Populate drop-drown lists and powering autocompletion fields was not possible. The best option would be to integrate directly with the underlying Wikibase API. Look at https://github.com/sparna-git/Sparnatural/issues/258 (I saw you already looked at it !)

I would love to hear about your progress with Wikidata integration, this is a wonderful use-case. Don't hesitate to ask other questions here.

> I am currently using JSON-based configuration, and I'd like to implement support for time properties (e.g. implement a "publication date" property: https://www.wikidata.org/wiki/Property:P577)
> I am not very sure how to proceed in that case. Should I call it an "@type" : "ObjectProperty" too and assign it as a subproperty of sparnatural:TimeProperty-Date?

Yes

> I could not find it at the documentation (https://docs.sparnatural.eu/JSON-based-configuration), am I missing something? Do you have any tips on how to proceed?

This is documented at  https://docs.sparnatural.eu/JSON-based-configuration#widget.

JSON configuration is used in our development test page that contains an example of every kind of property. Look at https://github.com/sparna-git/Sparnatural/blob/master/src/index.html#L407, this is what you need. Look in this configuration, you will find an example of everything I think.

JSON-based configuration is still fully supported, but if possible, I suggest you switch to OWL-based configuration.

**Comment by lubianat** [comment]
@tfrancart Indeed, the dropdowns are a major challenge for Wikidata, but we are trying to figure out alternatives (at least for some smaller domains). 

I'm also planning to use supernatural here https://github.com/obophenotype/cl.github.io/issues/5 btw. But then, no Wikidata, just FYI.

**Comment by tfrancart** [comment]
Excellent, keep us posted for both projects !
Side-note for dropdowns : I think Sparnatural can cache the list of values for dropdowns, if that can help speed things a bit.

**Comment by tfrancart** [comment]
I let you close the issue if your original question is answered.
