### ISSUE TITLE
"Could not render results with the table plugin" message

### ISSUE THREAD

**Issue by VladimirAlexiev** [sparna-git/Sparnatural#315]
This warning message leaves something to be desired:

`Could not render results with the table plugin, the results currently are rendered with the Table plugin.`

It's seen at #309 and https://sparnatural.eu/demos/demo-bnf/index.html

btw @tfrancart super cool tool !!
Looks like the Semantic Search we did for ResearchSpace in 2012-2014 and then was taken up by Metaphactory in their product.

**Comment by tfrancart** [comment]
This is rather related to https://github.com/sparna-git/Sparnatural-yasgui-plugins
I need to investigate further

**Comment by tfrancart** [comment]
Still here

**Comment by tfrancart** [comment]
Now fixed by setting the "defaultPlugin" config property of Yars

**Comment by matentzn** [comment]
I dont know if this is related, but I just got that same error message in the triply deployment of yasgui:

[Query](https://yasgui.triply.cc/#query=prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0Aprefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0Aprefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0Aprefix%20mondo%3A%20%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fmondo%23%3E%0A%0ASELECT%20DISTINCT%20%3Fentity%20%3Fentity_label%20%3Fgene%20WHERE%20%0A%7B%0A%0A%3Fentity%20rdfs%3AsubClassOf%20%5B%20rdf%3Atype%20owl%3ARestriction%20%3B%0Aowl%3AonProperty%20%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0004020%3E%20%3B%0Aowl%3AsomeValuesFrom%20%3Fgene%20%5D%20.%20%0A%3Fentity%20rdfs%3Alabel%20%3Fentity_label%20.%0A%0A%3Fentity%20rdfs%3AsubClassOf*%20%3Fvalue%20.%0AFILTER%20(isIRI(%3Fentity)%20%26%26%20STRSTARTS(str(%3Fentity)%2C%20%22http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_%22))%0AFILTER%20(isIRI(%3Fgene))%0A%7D%20LIMIT%2010%0A&endpoint=http%3A%2F%2Fsparql.hegroup.org%2Fsparql%2F&requestMethod=POST&tabTitle=Mondo%3A%20Diseases%20with%20Genes&headers=%7B%7D&contentTypeConstruct=application%2Fn-triples%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/7070631/235654696-eece5547-d36b-48d6-aac1-aa6d63db60e9.png">
