### ISSUE TITLE
fr.dbpedia demo broken

### ISSUE THREAD

**Issue by VladimirAlexiev** [sparna-git/Sparnatural#316]
https://sparnatural.eu/demos/demo-dbpedia-v2/index.html?lang=en returns this error
>Unable to get response from endpoint. Possible reasons:
>- Incorrect endpoint URL
>- Endpoint is down
>- Endpoint is not accessible from the YASGUI server and website, and the endpoint is not [CORS-enabled](http://enable-cors.org/)

http://fr.dbpedia.org/sparql responds ok.

**Comment by tfrancart** [comment]
use an http:// link, not https://, so http://sparnatural.eu/demos/demo-dbpedia-v2/index.html?lang=en
This might require you to empty your browser cache.
At some point I setup https://, but this was a disaster as it prevented all queries to be sent to http:// SPARQL services for security reasons, so I rollbacked, but some links remained in https://

I really need to fix this

**Comment by VladimirAlexiev** [comment]
- Emailed dbpedia-fr-contact@inria.fr to rehost to HTTPS
- Please change **DBPedia Museums** to use http for the endpoint (until they fix it) and add to the descr "Museums, Artworks and Painters. *Warning: this endpoint uses HTTP so you may experience some connection problems".

Now I was able to make a query, but both sample queries return no results.

**Comment by tfrancart** [comment]
That demo page was updated and runs fine, so I am closing this.
Please open other issues if you spot anything else.
Thanks
