### ISSUE TITLE
Bad variable name replacement in sub-criterias

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#320]
Do the following query:

![image](https://user-images.githubusercontent.com/2728945/173596053-80cef13e-2d06-4213-9cfb-a108f4218787.png)

- Select "Oeuvre"
- Change name of variable "Artwork_2" to "Oeuvre"
- The replacement in the SPARQL is wrong, the variable "Person_3" is replaced by "Oeuvre", line 10:

![image](https://user-images.githubusercontent.com/2728945/173596456-13e51c5c-c74c-4b6d-9a48-5039a201398d.png)

ping @antoine37120

**Comment by antoine37120** [comment]
@tfrancart tu peux tester ceci sur la branche issue-312

**Comment by tfrancart** [comment]
@antoine37120 ca n'a pas l'air de marcher, ni sur la branche issue-312 ni sur master...

**Comment by antoine37120** [comment]
@thomas, je viens de mergé master dans la branch issue-312.
Je ne sais pas si cela à réglé le soucis mais je n'arrive pas à reproduire l'erreur.

**Comment by tfrancart** [comment]
OK ca me va.
