### ISSUE TITLE
When a query reset is made, it would be nice to be able to reset the Yasqe SPARQL query editor

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#330]
Do we need another callback for this ? or do we use same callback and we send an empty/null query ?

**Comment by tfrancart** [comment]
I think this works in V8, to be confirmed with @SteinerPascal

**Comment by SteinerPascal** [comment]
It works but starts with the query:
```
SELECT DISTINCT * WHERE { ?sub ?pred ?obj. }
```
If this query is autoexecuted, then it might try to get everything from the KG.

possible solutions:
- Limit
 ``` SELECT DISTINCT * WHERE { ?sub ?pred ?obj. } LIMIT 1 ```
- Point to owl:Nothing
``` SELECT DISTINCT * WHERE { owl:Nothing ?pred ?obj. } ```

What is your opinion on this?
