### ISSUE TITLE
Notes on Sparnatural JSON model and conversion to SPARQL by lubianat

### ISSUE THREAD

**Issue by lubianat** [sparna-git/Sparnatural#347]
Hello! 

I am digging a bit deep to understand the code's details. 

I am taking notes for my future self (and collaborators on Sparnatural-related projects) here: 

https://docs.google.com/document/d/1oMHYF6fEyp61s25i_vSUpRssmIGm60rmoy8cmG2qhY0/edit?usp=sharing

Maybe these notes can help someone as documentation. 

Also, most of the code is great (congratulations again!), but some bits are harder to understand than the rest. This bit, for example, perhaps could be refactored for clarity: 
* https://github.com/sparna-git/Sparnatural/blob/84c38d28e1bbc16cdcba74a51be39422e4c38741/src/Query.js#L264-L355

If it is useful, I can list the places that I found hard to read somewhere too (and perhaps in the future help refactoring, if wanted :) )

**Comment by lubianat** [comment]
A note: I am not as fluent in JS as I am in other languages, so the nomenclature might be incorrect here and there.

**Comment by tfrancart** [comment]
Hi @lubianat a major code refactoring in Typescript is taking place at https://github.com/SteinerPascal/sparnatural-port thanks to @SteinerPascal so you might want to take a look there. Hpefully the Typescript version will one day replace the Javascript version.

The part of the code you point handles the "defaultLabelProperty" annotation and automatically adds a criteria to automatically fetch a label for the selected classes.

**Comment by tfrancart** [comment]
Also @lubianat make sure you have read https://docs.sparnatural.eu/Query-JSON-format
In the current port in Typesript, the SPARQL query generation does not happen from the JSON structure but from the Typescript widget class, which has been a long subject of discussion between me and @SteinerPascal

**Comment by lubianat** [comment]
Closing it as it is quite outdated.
