### ISSUE TITLE
Ability to display a hierarchy of classes and propertis (2 levels)

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#351]
Either with this UX proposal:

![Liste 1](https://user-images.githubusercontent.com/2728945/189690407-892aa8e3-62cb-42bf-bb44-15301ba6e536.png)

Or with that:

![Liste 2](https://user-images.githubusercontent.com/2728945/189690444-dfa3cf32-2600-408c-901b-5a7a3810245e.png)

**Comment by tfrancart** [comment]
Detailled specification document : [specs-detaillees-v2.docx](https://github.com/sparna-git/Sparnatural/files/12819226/specs-detaillees-v2.docx)

**Comment by tfrancart** [comment]
1. Thomas : Faire une version hiérarchisée de la config B des AN pour test
2. Thomas : Faire évoluer les SpecProvider pour ajouter des méthodes permettant de récupérer l'information de hiérarchie dans la config

**Comment by tfrancart** [comment]
@antoine37120 quelques notes de spécifications pour le composant de colonnes de Miller:

# Spécification pour le fonctionnement du composant "Colonnes de Miller"

## Spécifications

### UI

- Il faut que le composant marche pour une hiérarchie avec un niveau de profondeur arbitraire, mais typiquement 3 ou 4 niveaux de profondeurs
- Il faut gérer les listes longues dans un niveau (scroll vertical)
- Il faut bien voir le "fil d'Ariane" de la hiérarchie, cliquable pour remonter à un niveau supérieur
- On doit pouvoir spécifier le nombre de colonnes visibles
  - Par défaut, ce sera 3
  - Le composant doit marcher avec une seule colonne
- Il faut pouvoir passer une méthode de callback qui s'exécutera quand un noeud sera sélectionné
- Sur chaque noeud, il faudra pouvoir :
  - ouvrir le noeud pour afficher les enfants
  - sélectionner le noeud
    - Il faut pouvoir sélectionner un niveau intermédiaire dans la hiérarchie (pas seulement une feuille)
  - afficher des infos supplémentaires sur le noeud (cf https://github.com/sparna-git/Sparnatural/issues/434#issuecomment-2082457393)
- Il faut pouvoir facilement faire un "Back" pour remonter
- Il faut bien gérer :
  - la présence d'icônes FontAwesome
  - les tooltips de définition (ou remplacement par l'infobulle d'infos supplémentaires)
- Il faut bien gérer l'intégration dans la barre de critères du dessus, c'est-à-dire qu'on ait bien le lien visuel entre l'arborescence qui permet la sélection, et la flèche qui se remplit une fois la sélection effectuée
- On doit pouvoir "disabler" des entrées, qui ne pourront pas être sélectionnées
- (dans une V2) On devrait pouvoir réafficher le composant avec une entrée déjà sélectionnée (pour éditer une sélection qui aurait déjà été faite)
- Il faut que tous les libellés soient internationalisables

### Data

- Il faut que le composant puisse s'initialiser en lisant une structure de données JSON hiérarchique
- Il faut que le composant puisse s'initialiser en lisant des listes HTML (`<ul>`, `<ol>`, `<li>`)
  - Dans ce cas, on construira la structure de données JSON correspondante pour se ramener à une initialisation JSON
- (en V2) il faudra que le composant puisse récupérer les enfants dynamiquement, au clic (similaire à l'arbre JQuery actuel)

**Comment by tfrancart** [comment]
Latest mockups: https://www.figma.com/proto/YEWYuMrBXLimTqyEUyPKZl/Sparnatural_OptimMenu?node-id=138-2257&t=tPi1ApEJ1chf5Beg-9&starting-point-node-id=138%3A2257&show-proto-sidebar=1

**Comment by antoine37120** [comment]
@tfrancart,
Périmètre couvert par les derniers commits :  
- La sélection de class fonctionne pour StartClass et EndClass
- La sélection auto si ajout des clause And ou Where.
- L'affichage de l'icon du parent si pas d'icon associé à la class
- Support des items disabled
- Affichage du widget si suppression de EndClass

A regarder en priorité => la fonction ISpecificationEntity : getConnectingPropertiesTree renvoie finalement un Dag vide.

**Comment by tfrancart** [comment]
1. Le disabled ne doit pas s'implémenter comme ça : regarde la maquette numéro 3:

![image](https://github.com/user-attachments/assets/b7287a2e-0bbf-4f2f-bc0b-1b16ccdcaa1a)

ici "Etude Notariale" est disabled, il n'y a pas de séparation avec la flèche et le libellé n'est pas grisé. Au clic sur le libellé on descend dans le niveau du dessous

2. Le problème dans la construction de l'arbre des propriété est corrigé
3. J'ai modifié la méthode getIcon pour renvoyer seulement le code d'icône, il faut que tu ajuste de ton côté pour recréer le code HTML
4. Tu peux utiliser ca pour avoir une config plus riche:


            

(c'est commité dans index.html ligne 62)

**Comment by antoine37120** [comment]
Thomas,

J'ai corrigé le comportement pour les disabled et réimplémenter pour les icons.
Merci pour la nouvelle config

Je crois qu'il me reste à implémenter : 
La sélection avec l'object property
Animer différemment le fil d'Ariane
Recharge d'une requête
Et vos dernier retours concernant les petits détails cosmétiques.

Je priorise sur la sélection de l'object property

**Comment by antoine37120** [comment]
@tfrancart Je viens de pousser la sélection des objects Property.

As tu un exemple précis pour explorer une arborescence de propriétés ?

**Comment by tfrancart** [comment]
Merci pour tout ça  ! j'ai regardé :

1. Les icônes dans le sélecteur arborescent sont tout petits et ils ont rapetissés aussi dans la flèche de critère :-) avant on mettait `font-size: 170%` autour. Peux-tu remettre un icône plus grand ?

taille actuelle:

![image](https://github.com/user-attachments/assets/e3e49f38-a052-4a35-a127-a4140c86cee9)

taille dans le sélecteur

![image](https://github.com/user-attachments/assets/a030ffaa-de5b-4bdf-92dc-9e22ae3f7f7d)


2. Comme dans la maquette, il faudrait colorer légèrement les zones dans la ligne de critère où on voit "chercher des ressource", pour le sujet, l'objet, et la property


![image](https://github.com/user-attachments/assets/4bb121d3-944f-4147-b134-57b3febafbfa)


3. Le placeholder "chercher des ressources" ne doit se trouver que sur la partie sujet, pas sur le sélecteur pour l'objet, ni sur le sélecteur de propriété

![image](https://github.com/user-attachments/assets/41a1ddb5-5c01-42bc-91ec-117541c1779d)

4. La largeur de la première liste où il y a seulement 2 éléments me fait bizarre. C'est très large. Je me demande si on ne devrait pas avoir un sizing un peu différent si la liste est plate (sans hiérarchie) ? à discuter

5. Je n'ai pas de cas pour une arborescence de propriétés

6. Ca bugge quand je choisis "File > Concept --> DocumentaryFormType", l'arbre des propriétés ne se charge pas bien:

![image](https://github.com/user-attachments/assets/9117e112-46d7-454b-8739-7bd8aa506c29)

`listToDisplay is null` - peut-être un problème dans ce qui est ramenée par la fonction de lecture.

**Comment by florenceclavaud** [comment]
Bonjour @antoine37120 et @tfrancart, petite suggestion : pour avoir un cas d'arborescence de propriétés, vous pourriez utiliser les fichiers RDF (RiC-O 0.2) des agents (notaires et études notariales) qu'on a publiées dans le démonstrateur des AN.
Les données sont là : [https://github.com/ArchivesNationalesFR/Sparnatural_prototype_data/tree/main/RDF/imported_data/creators_and_accumulators](https://github.com/ArchivesNationalesFR/Sparnatural_prototype_data/tree/main/RDF/imported_data/creators_and_accumulators)
La propriété de niveau 1 pourrait être rico:isAgentAssociatedWithAgent.
En-dessous il pourrait y avoir rico:hasFamilyAssociationWith (entre 2 personnes); rico:hasSuccessor (entre une personne et un organisme) et rico:precedesInTime (entre 2 personnes)
Cela fait 2 niveaux, c'est toujours ça.

**Comment by antoine37120** [comment]
@tfrancart une première version du fil d'Ariane animé peut être testé. Reste à voir ce que ça donne avec une hiérarchie plus profonde que celle de la config actuelle. Ce n'est pas tout à fait terminé.

La taille des icons sont fixés et j'ai ajouté un fond pour le placeholder.

Et d'ailleurs comme on a décidé de gérer l'affichage de valeurs par StartClass, EndClass et ObjectProperty, je te propose de traiter aussi le placeholder dans ces mêmes class du script.

Next step => affichage des valeurs sélectionnées à traiter différemment...

**Comment by tfrancart** [comment]
@antoine37120 je viens de faire un push avec un test pour une hiérarchie à 3 niveaux:

![image](https://github.com/user-attachments/assets/cd6fc03a-60cf-4a1c-ae57-df8282f6cf1a)

**Comment by tfrancart** [comment]
> une première version du fil d'Ariane animé peut être testé. Reste à voir ce que ça donne avec une hiérarchie plus profonde que celle de la config actuelle. Ce n'est pas tout à fait terminé.

Trop beau !

> Et d'ailleurs comme on a décidé de gérer l'affichage de valeurs par StartClass, EndClass et ObjectProperty, je te propose de traiter aussi le placeholder dans ces mêmes class du script.

Oui oui parfait !

**Comment by antoine37120** [comment]
> @antoine37120 je viens de faire un push avec un test pour une hiérarchie à 3 niveaux:
> 
> ![image](https://private-user-images.githubusercontent.com/2728945/364710287-cd6fc03a-60cf-4a1c-ae57-df8282f6cf1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1Mjg1NzIsIm5iZiI6MTcyNTUyODI3MiwicGF0aCI6Ii8yNzI4OTQ1LzM2NDcxMDI4Ny1jZDZmYzAzYS02MGNmLTRhMWMtYWU1Ny1kZjgyODJmNmNmMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDkyNDMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzkxMzc5MzczMWJmMDM4Yzc2OTgwNDFkOGY0NmFhYTczZjU2NGZlNTIzNzFkMjAzYjVjMjYzYjhlYWNjZGQwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TZOimPnf-WAo1xT14tNMzVVQdvWXFzo6URPqH9KLMeI)

@tfrancart  Ah, il nous en faut au moins 4... aux fonds des fonds ;-)

**Comment by tfrancart** [comment]
> @tfrancart Ah, il nous en faut au moins 4... aux fonds des fonds ;-)

C'est fait !

![image](https://github.com/user-attachments/assets/2e256ee4-457b-48c0-84ba-2f0cb309ce30)

1. A ce niveau le fil d'Ariane devrait être `Fonds / Record Set`
2. Il y a des problème quand on remonte, les flèches descendantes ne s'affichent plus et les fils d'Ariane ne s'affichent plus

**Comment by antoine37120** [comment]
@tfrancart Les 2 derniers points son traités.

Je crois que l'implémentation est complète pour le fil d'Ariane

<img style="max-width: 100%;" alt="image" src="https://github.com/user-attachments/assets/3343c635-905a-481a-8ec9-01200abf2ab6">

**Comment by tfrancart** [comment]
Nos notes:

- Voir l'animation sur le fil d'Ariane qui semble ne pas se déclencher tout le temps (ca a l'air aléatoire)
- Aligner le sélecteur sur le placeholder à gauche
- Voir si la largeur du placeholder peut être identique au widget
- Laisse le placeholder "related to" dans le ObjectPropertyId
- Compter le nombre de caractère et afficher un tooltip si > x
- Intégrer les tooltips tippy dans le menu de sélection - voir l'intégration dans le fichier nice-select ligne 127. Si le libellé est trop long et qu'il y a un tooltip, on assemble les deux

**Comment by tfrancart** [comment]
@antoine37120  j'ai corrigé le bug sur les propriétés parfois vides.
j'ai aussi vu qu'il y a une erreur quand on fait un WHERE, la sélection de la classe du dessus n'est pas bien reportée:

![image](https://github.com/user-attachments/assets/7fdcb5ac-e8cb-454d-83c4-f433fad35483)

Erreur console:
```
Uncaught TypeError: allWithId[0] is undefined
    submitSelectedValue HierarchicalClassSelectBuilder.ts:419
    submitSelected ClassTypeId.ts:105
    addWhereComponent AddWhereComponent.ts:32
    _GroupWrapperEventStore_registerGrpWrapperEvents GroupWrapperEventStore.ts:60
``` 

Par contre pas de souci sur le AND.

**Comment by antoine37120** [comment]
@tfrancart A propos de "Voir l'animation sur le fil d'Ariane qui semble ne pas se déclencher tout le temps (ca a l'air aléatoire)", à tester de ton côté. Chez moi tout allait déjà bien avant. Je n'ai pas pu reproduire.
Cependant il y a u une petite modification pour retarder un changement de class sur un élément en cour d'insertion dans le DOM.
A toi de me dire si ça porte ses fruits.

**Comment by antoine37120** [comment]
@tfrancart Ca me semble être bon pour tout tester.
Il ne reste que le rechargement de requête à implémenter de mon côté

**Comment by antoine37120** [comment]
@tfrancart Est ce que c'est derniers ajustements te conviennent ?

A propos du point : Je vois que la largeur du composant est plus petite sur la sélection de proprétés, très bien. Mais pourquoi n'est-elle pas plus petite sur la première liste qui contient seulement Instantiation et File ? car elle est aussi à plat (mais avec un icône).

Pour être claire sur le mode de calcule de la largeur,
celui-ci prend en compte si on a pas : 
- D'icon => - 48px (largeur des icons quand affichés)
- D'enfants à explorer => -30px (largeur des boutons pour descendre dans la hiérarchie.

Donc si il y a un ou des icons la réduction n'est pas maximale.

Voici comment cela est appliqué en css : 
```css
        .currentWrapper {
           span.current {
		min-width: 345px;
           }
	}
        &.selectorIsFlat { // Si liste plate  -30px
            .currentWrapper span.current {
                min-width: 315px;
            }
        }
        &:not(.selectorHasIcon) { // Si pas d'icon -48px
            .currentWrapper span.current {
                min-width: 297px;
            }
        }
        &.selectorIsFlat:not(.selectorHasIcon) {// Cumul des critères -48px -30px
            .currentWrapper span.current {
                min-width: 267px;
            }
        }
```

Peut être veux tu simplement que l'on rogne davantage quand il n'y a pas de hiérarchie : -30px => -48px ?

**Comment by antoine37120** [comment]
@tfrancart Et le rechargement de requête est maintenant fonctionnel.

Tout le gros œuvre est fait ;-)

**Comment by tfrancart** [comment]
@antoine37120  Merci ! Toujours le centrage du placeholder de propriétés :

Avant, c'est centré

![image](https://github.com/user-attachments/assets/3b2b738e-a030-4063-9aca-c0a3a6132e14)

Pendant, c'est plus centré:

![image](https://github.com/user-attachments/assets/4eafe837-27d7-423d-bae9-ba9bea23b24d)

En fait, je propose de ne pas mettre du tout ce placeholder (comme pour la sélection du EndClass)


Et peux-tu également regarder les Draggables de colonnes pour ajuster l'affichage de leur icône ? merci merci:

![image](https://github.com/user-attachments/assets/ae3e8c47-4bc0-4a11-966e-26ddac292971)

j'ai testé le rechargement de requête, ça fonctionne bien

**Comment by antoine37120** [comment]
@tfrancart Je vien d'ajouter l'affichage des count avec des valeurs aléatoires pour voir ce que cela donne jusqu'à e qu'il y ai des counts dans la config. Donc tu peux tester comme ceci.

Il y aura donc 2 fichiers à éditer : 
- [ObjectPropertyTypeId.ts](https://github.com/sparna-git/Sparnatural/commit/1191bbf41781f867d568359a4905ff97d88a98d4#diff-182bb094454fd9a5b287e0a482fb37c6c56bd8bd46825e86f1fb99c6022f0d5f)
- [ClassTypeId.ts](https://github.com/sparna-git/Sparnatural/commit/1191bbf41781f867d568359a4905ff97d88a98d4#diff-0d557890176d9de920902288f9dbf821b77b5a72d05d4015ca2a48be8b2f12ae)

Et mettre à disposition la fonction renvoyant le count à partir de la propriété payload de l'objet Dagnode.
```js
element.payload.getCount() ;
```
Il y aura donc que ces deux fichiers à éditer une fois que la fonction sera disponible.
Si pas de count, la valeur de retour attendue est undefined.

Le formatage des valeurs pour l'affichage ce fait ici : https://github.com/sparna-git/Sparnatural/commit/1191bbf41781f867d568359a4905ff97d88a98d4#r146618503

A partir de 1000 et les valeurs sont en nombre de milliers ou de millions. En dessous de 1000 la valeur brute est affichée.

**Comment by tfrancart** [comment]
@antoine37120 j'ai intégré les count. Pourras-tu faire la petite modification de couleur évoquée avec Aurélien ? (mettre la barre en orange plus light, et la passer en orange plus soutenu au hover. 
Je ne suis pas sûr qu'on garde la taille des barres relative comme cela, mais il nous faut un peu plus de recul et d'expérience pour voir comment ça se comporte.

**Comment by tfrancart** [comment]
@antoine37120 j'ai vu également que la fonction `convertToJsonDag` était dupliquée dans ClassTypeId et ObjectTypeId. Peux-tu faire en sorte de n'en garder qu'une version ?

**Comment by antoine37120** [comment]
@tfrancart  Pour la fonction dupliquée, pourquoi pas l'ajouter dans src/sparnatural/dag/Dag.ts ?
