### ISSUE TITLE
docker-compose build failing in Linux environment

### ISSUE THREAD

**Issue by asharies97** [sparna-git/Sparnatural#356]
I'm trying to install Sparnatural on an Amazon EC2 running "Amazon AMI 2". 
The docker-compose build is not getting completed and failing with the following error: 

_failed to solve: failed to compute cache key: "/package-lock.json" not found: not found_

![Sparnatural-Docker-compose issue](https://user-images.githubusercontent.com/26801872/195295518-8e1ff274-5108-4948-8567-23f365479b1c.jpg)

**Comment by tfrancart** [comment]
I am unable to maintain Docker packaging, so closing.
