### ISSUE TITLE
Add loading component (merge or port #215 to v8)

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#368]
If a datasource is queried by a widget, render a loading component till the datasource is loaded.

Sometimes for list/autocomplete widgets, it takes a while to load. Bridge this time with a loading component. Otherwise it might be confusing and the user doesn't know if something is the datasource is broken or still loading

--> This we had done already : https://github.com/sparna-git/Sparnatural/issues/215 but **not merged**. and the related commits : https://github.com/sparna-git/Sparnatural/commit/e85454be97ea6b29126c9a77192abf735c9b7461 and https://github.com/sparna-git/Sparnatural/commit/cf246009a8e142aa82147fd40a9eaadf9ec6295b

This needs to be ported to v8

**Comment by SteinerPascal** [comment]
I'm taking this off your shoulders =)

**Comment by SteinerPascal** [comment]
Hi @tfrancart or @antoine37120,
Could you provide me with a screenshot on how the styling is supposed to look like?
