### ISSUE TITLE
Segregate widget value selection from RDFJs pattern creationg

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#377]
Currently the widgets come with a certain RDFjs pattern. this limits the widget to a certain pattern if patterns should be added it has to be added in the code. 
Decouple widgets into two parts.
1. value selection (list, map, date etc.)
2. rdfjs creation (values with uris, geo filters, date filter etc.)

It would then be possible to mix them. For example: use to list widget to create geo filters and not only values with URIs.

**Comment by tfrancart** [comment]
The decoupling should be between the widget and the widget value : multiple widgets can produce the same widget value (e.g. List and Autocomplete both produce a URI as a value). Then for a given WidgetValue, the SPARQL generation is always the same.
And, in your proposal, the same Widget could produce different WidgetValue but based on which criteria ? I would argue that this would actually correspond to a new kind of Widget (say "ListSelectionGeoWidget"), that has its own code, and then generate the same WidgetValue as the MapWidget.

**Comment by tfrancart** [comment]
We are getting close to this with the separation of the sparqljs pattern generation from the actual widget code (https://github.com/sparna-git/Sparnatural/commit/ee4e823d4cd8ff1bf5e56f53e2c34041beab6298 and the new class ValueBuilder). Now the widget code is only the widget and produces the WidgetValue, and then the SPARQL generation converts the value to SPARQL.
