### ISSUE TITLE
Reset button disappear if we remove first row from the query

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#385]
I create a query with 2 rows using an AND.
I remove the first row.
The second row becomes the first row, but the reset button has disappeared:

Before:

![image](https://user-images.githubusercontent.com/2728945/202510980-157eee27-a763-412a-b77d-50943e3f7f84.png)

And after removing first row:

![image](https://user-images.githubusercontent.com/2728945/202511060-d7885e75-386d-43f1-8e5b-39fa33747b3c.png)

**Comment by SteinerPascal** [comment]
I'm not able to reproduce the error... In my case it works. Does this happen in any situation?

**Comment by tfrancart** [comment]
it seems the behavior has changed : now when I delete the first row, its AND sibling is also deleted. I don't think this is the intended behavior. When a row is deleted, its **children** should be recursively deleted, but its **siblings** connected with an AND should remain.

**Comment by tfrancart** [comment]
Yes, the behavior of the deletion is inconsistent : if I delete a line, all its following ANDs get deleted. This is not what should happen; if I delete a line, all its **subtree** should get deleted, but the following AND siblings should remain and "go up" one level (that is, the andSibling of the parent of the deleted line should be set to the andSibling of the deleted line)
