### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by EnnoMeijers** [sparna-git/Sparnatural#386]
Hi,

When I follow the install instructions and run the **docker-compose build** command the process fails with the following error:
```
Step 5/14 : COPY package-lock.json /usr/src/app/
ERROR: Service 'sparnatural' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat package-lock.json: file does not exist
```

Thnx,
Enno

**Comment by tfrancart** [comment]
Hello @EnnoMeijers we don't plan to continue supporting the docker packaging anymore

**Comment by EnnoMeijers** [comment]
Ok, clear! I think it is a minor issue, I will send an update when I can fix it.

**Comment by SteinerPascal** [comment]
@EnnoMeijers This happens because you first need to do a `npm install`. Then the file package-lock.json gets created. Without it the command in the Dockerfile fails since it can not find the package-lock.json.

**Comment by SteinerPascal** [comment]
closing this as it seems stale
