### ISSUE TITLE
Local build fails

### ISSUE THREAD

**Issue by EnnoMeijers** [sparna-git/Sparnatural#387]
Building a local version following the https://docs.sparnatural.eu/Developing-and-Compiling documentation fails.

Running **npm run start** throws the following error:

```
ERROR in ./node_modules/n3/node_modules/readable-stream/lib/internal/validators.js 140:15
Module parse failed: Identifier directly after number (140:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

Using npm version 8.19.1 and node version v14.19.2.

**Comment by tfrancart** [comment]
Strange indeed, I confirm I can reproduce the same behavior.
I can't find a fix now, but anyway we will soon be transitioning to a new major version in Typescript, currently on branch "issue-298-TS". Would you mind checking out this branch and try to compile from here ? If you want to look at the code and do modifications, you should start from this Typescript version as the javascript version will soon be deprecated.
I just double checked from a fresh checkout on this branch, and compilation works fine

**Comment by EnnoMeijers** [comment]
Thanks for your reply. Using the "issue-298-TS" branch worked for me too!
