### ISSUE TITLE
aggregation queries (COUNT etc.)

### ISSUE THREAD

**Issue by asanchez75** [sparna-git/Sparnatural#398]
Hi,

First of all, thanks for this amazing tool!
I wonder if there is a roadmap to implement "aggregation queries" (GROUP BY, COUNT, AVG, SUM, etc) .
If there is not, may you share some information about how to extend Sparnatural to support it?

Thanks,

**Comment by tfrancart** [comment]
Hello @asanchez75 

Aggregation queries are in the back of our minds, yes. Maybe in 2023 ? The developement will be driven by end-user needs, so probably only COUNT, and not all aggregation functions.

Please be aware that we are currently transitioning to Typescript, currently in branch "issue-298-TS" so please look a the code in this branch. Merge on master should happen end december / early january.

Don't hesitate to share your questions, remarks, needs and use-cases here.

**Comment by tfrancart** [comment]
A few mockups for this feature (nothing definitive) : 
[maquette_count.pptx](https://github.com/sparna-git/Sparnatural/files/13712886/maquette_count.pptx)

We will work on this early 2024.

**Comment by tfrancart** [comment]
What SQL query generators are doing:

![DBHawk-Ad-Hoc-Reporting-min](https://github.com/sparna-git/Sparnatural/assets/2728945/76311584-ddc1-43d4-88c1-a13ecb94df29)

![rsqd-relational-graphical](https://github.com/sparna-git/Sparnatural/assets/2728945/c7e0284b-ad6e-45e9-b0f9-fca03b25ad11)

![rs-tablixareas](https://github.com/sparna-git/Sparnatural/assets/2728945/089fe302-17dd-4dc1-9d56-d0347e7001c0)

**Comment by florenceclavaud** [comment]
Thanks for sharing this! I am not sure I would be able to choose between those options just now. I would probably not choose option 2. IMHO the most important would be to let end users understand what COUNT(?archive_1) means directly in the form before running the query, which may be difficult for a person who does not know SPARQL. Maybe a tooltip could be associated with each of the values in the list. 
Also, once an end user gets the results from the COUNT query, he/she may want to go further; would it be possible to just switch from `?Archive_1_count` to `?Archive_1`,  without canceling the whole query and redoing everything (and vice-versa)? Sorry if I am not clear.
Also, I suppose the list of values (COUNT, GROUP_CONCAT, SUM, etc.) could be configured so that, for example, some values would not be available as they would not be appropriate.
My two cents..

**Comment by tfrancart** [comment]
We need to specify how this will be represented in Sparnatural JSON structure.
For information sparqljs aggregate representation is the following

```json
    // SELECT (COUNT(?o2) AS ?o2_count)

    {
      "expression": {
        "type": "aggregate",
        "aggregation": "count",
        "distinct": false
        "expression": {
          "termType": "Variable",
          "value": "o2"
        },        
      },
      "variable": {
        "termType": "Variable",
        "value": "o2_count"
      }
    }
```

**Comment by tfrancart** [comment]
C'est OK pour moi, merci

**Comment by tfrancart** [comment]
Salut @antoine37120 on peut prendre exactement la même structure JSON que celle plus haut pour le cas des aggrégations.

Voici un exemple complet, si on voulait compter le nombre d'archives (Archive_1) par type de document:

![image](https://github.com/sparna-git/Sparnatural/assets/2728945/ac40259a-e23e-4ffd-b95d-f98ee933dc9c)

```json
{
  "distinct": true,
  "variables": [
    {
      "expression": {
        "type": "aggregate",
        "aggregation": "count",
        "distinct": false
        "expression": {
          "termType": "Variable",
          "value": "Archive_1"
        },        
      },
      "variable": {
        "termType": "Variable",
        "value": "Archive_1_count"
      }
    },
    "?TypeDeDocument_2"
  ],
  "defaultLang": "fr",
  "order": null,
  "branches": [
    {
      "line": {
        "s": "?Archive_1",
        "p": "https://sparna-git.github.io/sparnatural-demonstrateur-an/ontology#aPourTypeDeDocument",
        "o": "?TypeDeDocument_2",
        "sType": "https://sparna-git.github.io/sparnatural-demonstrateur-an/ontology#Archives",
        "oType": "https://sparna-git.github.io/sparnatural-demonstrateur-an/ontology#TypeDeDocument",
        "values": []
      },
      "children": []
    }
  ]
}
```

Alors oui je sais dans la partie "expression" on n'utilise pas de "?", et quand la variable est toute seule on en met un. Nous pourrions normaliser pour n'en mettre nulle part, éventuellement.

**Comment by tfrancart** [comment]
@antoine37120 merci

1. Ne pas mettre de transparence sur la pastille:

![image](https://github.com/sparna-git/Sparnatural/assets/2728945/2f21935e-8b57-4535-9ca7-29df6dc7591c)

2. Mettre un espace plus important à gauche de la flèche:

![image](https://github.com/sparna-git/Sparnatural/assets/2728945/5726688f-741a-4bb6-8f94-f3c26cf6baa5)

3. Quand une fonction est sélectionnée, modifier le nom de la variable finale en ajoutant ce suffixe à la fin du nom de variable:

COUNT : xxx_count
SUM: xxx_sum
MIN : xxx_min
SAMPLE: xxx_sample
GROUNP_CONCAT: xxx_group_concat
AVG: xxx_avg

4. Attention, c'est GROUP_CONCAT, pas GROUP_COMCAT

5. Gérer l'export en JSON (cf commentaire ci-dessus)

6. Si j'édite le nom de la variable, le nom de la variable dans le COUNT est modifié, mais il ne faut pas:

![image](https://github.com/sparna-git/Sparnatural/assets/2728945/976658b5-4bba-47c9-b649-0a77c455b728)

7. Pouvoir gérer des libellés français / anglais des fonctions

**Comment by tfrancart** [comment]
8. Si la property n'est *pas* de type "NumberProperty" ( `specProvider.getProperty(xxxx).getPropertyType()` ) , griser les fonctions SUM, MAX, MIN et AVG

**Comment by tfrancart** [comment]
9. Dans la UI, si une fonction d'aggrégation est sélectionnée, il faut interdire que l'utilisateur puisse renommer la variable avec le même nom de variable que la variable d'origine

**Comment by tfrancart** [comment]
Un exemple de query pour tester le load (doit activer un count sur ProvidedCHO_1 qui est la 2ème colonne) :

```json
{
  "distinct": true,
  "variables": [
    "ZZ_Other_2",
    {
      "expression": {
        "type": "aggregate",
        "aggregation": "count",
        "distinct": false
        "expression": {
          "termType": "Variable",
          "value": "ProvidedCHO_1"
        },        
      },
      "variable": {
        "termType": "Variable",
        "value": "ProvidedCHO_1_count"
      }
    }    
  ],
  "order": null,
  "branches": [
    {
      "line": {
        "s": "?ProvidedCHO_1",
        "p": "https://shacl-play.sparna.fr/shapes/ProvidedCHO_type",
        "o": "?ZZ_Other_2",
        "sType": "https://shacl-play.sparna.fr/shapes/ProvidedCHO",
        "oType": "http://special/ZZ_Other",
        "values": []
      },
      "children": []
    }
  ]
}
```

**Comment by antoine37120** [comment]
@tfrancart nous avons maintenant un type pour chaque variable qui peut permettre de préciser quelles fonctions d'agrégations sont les plus adéquates ?
```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?WebResource_1 ?Z_Number_2 ?Aggregation_4 ?Z_Text_6 WHERE {
  ?WebResource_1 rdf:type <http://www.europeana.eu/schemas/edm/WebResource>;
    <http://purl.org/dc/terms/extent> ?Z_Number_2;
    <http://www.openarchives.org/ore/terms/isAggregatedBy> ?Aggregation_4.
  ?Aggregation_4 rdf:type <http://www.openarchives.org/ore/terms/Aggregation>.
  ?WebResource_1 skos:altLabel ?Z_Text_6.
}
LIMIT 100
```

```js
console.log(selected_val) =>  {type: 'http://special/Z_Number', variable: 'Z_Number_2'}
console.log(selected_val) => {type: 'https://shacl-play.sparna.fr/shapes/Aggregation', variable: 'Aggregation_4'}
console.log(selected_val) => {type: 'http://special/Z_Text', variable: 'Z_Text_6'}
```
