### ISSUE TITLE
Naming of core:NotInstantiatedClass

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#422]
@tfrancart,
The specs show that a class can be used for traversing through the graph without appearing in the sparql selection. Two questions to this.
1. Naming: In the code this is specified with `isRemoteClass`. I would like to rename it to `isNotInstantiatedClass`. 
2. Should we prevent widget creation for `NotInstantiatedClass`es? What is the behavior? I guess it is still possible to trigger further WHERE childs.

Let me know what you think.

**Comment by tfrancart** [comment]
This flag is used to mark resources that do not have a type in the KG, and thus that should have a corresponding rdf:type condition in the SPARQL clause.

Yes, renaming the method would be good (I hesitated on the naming).
I would suggest not automatically preventing widget creation; even if the resource is not described in the KG one could want to select it based on its URI (we do have this use-case actually). It is the config responsibility to drive the widget based on the properties, and set the properties as "NonSelectableProperties".
WHERE childs are indeed possible.

**Comment by SteinerPascal** [comment]
Okay thanks
