### ISSUE TITLE
Submit Action gets called twice

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#425]
When the submit btn is clicked then it calls the PlayBtn callback once BUT the method `submitAction` gets called twice. this causes yasqe to fail and the playbtn stays greyed out.

**Comment by tfrancart** [comment]
Haaaaa great, thanks for catching this !
Note : it is normal that the playbtn stays greyed out after executing the query ! It is re-enabled as soon as you change something in the query

**Comment by SteinerPascal** [comment]
Okay cool. I have fixd it. I found something i don't quite understand.
https://github.com/sparna-git/Sparnatural/blob/e3d1ab5d13ab8a1d6a8a6d500a0aa4df28933ff6/src/sparnatural/components/buttons/PlayBtn.ts#L25-L26

There are two classes added there and they seem contratictive. And it causes the enablePlayBtn method to not have any effect.
Is this a mistake?

**Comment by tfrancart** [comment]
Yes yes yes this is normal. The states of the buttons are:

1. It is active, green
2. When query is executed, it shows the spinner
3. Once the query has finished, it is greyed out and inactive. The query cannot be re-executed until it is modified
4. As soon as the query is modified, the button gets reactivated (this is done through the enable() function
