### ISSUE TITLE
Service enabled mixed with an OptionState

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#428]
If we have an objectproperty with a service endpoint it colors the criteriagroup and the descendants light blue. But as soon as we activate an option state such as OPTIONAL or NOTEXISTS, it starts to loose the state and light blue color. Do we need to have a combined state and dashed line? so we can mix SERVICE with OPTIONAL or NOTEXISTS?

**Comment by tfrancart** [comment]
> Do we need to have a combined state and dashed line? so we can mix SERVICE with OPTIONAL or NOTEXISTS

No, let's keep thinks simple and decide that one has precedence on the other. It looks OK the way you describe it, OPTIONAL or NOT EXISTS takes precedence on SERVICE. Also the fact that a given property is "remote" can be in its label e.g. "wikidata position", or somthing like that

**Comment by SteinerPascal** [comment]
Okay i had to make a fix cause it would never go back to light blue after an OPTIONAL or NOTEXISTS. see: 9649f47a9b03c7a60beb436ae8d445df22b45b03
