### ISSUE TITLE
It is not possible to use a property path in typePredicate anymore

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#440]
See #72 and #439 
The problem is that now we are using strong typing to construct the SPARQL query, not just a plain string.
We need to explicitely build a PropertyPath to construct the type triple, at https://github.com/sparna-git/Sparnatural/blob/master/src/sparnatural/generators/helpers/ClassBuilder.ts#L58

Probably we could try to parse the actual typePredicate string with the SPARQL parser so that it yields either a Predicate or a PropertyPath ?

**Comment by SteinerPascal** [comment]
That's exactly what i thought as well. I'll do it
