### ISSUE TITLE
"Bigger than X" literal property with numeric value handling similar to how dates are handled?

### ISSUE THREAD

**Issue by lubianat** [sparna-git/Sparnatural#451]
Hello again!

I am taking a look at the documentation and trying to figure out ways to introduce properties with numeric values on Sparnatural. 

The particular use case is a Sparnatural interface to query cars on Wikidata (e.g. https://www.wikidata.org/wiki/Q111666705), searching, for example, for all models with a height over 1700 mm. 

Is there a way to do numeric queries on Sparnatural?  Thanks!

**Comment by tfrancart** [comment]
> Is there a way to do numeric queries on Sparnatural? Thanks!

Not currently but this on our radar for the upcoming months : https://github.com/sparna-git/Sparnatural/issues/170 (in French, sorry)
This is probably not too complicated so we could put higher priority on this

**Comment by tfrancart** [comment]
Hi @prashydee indeed we are thinking about something similar to the existing widgets for dates, except it would work for numeric values:

![image](https://user-images.githubusercontent.com/2728945/234585239-3bfe9c30-5a8e-4490-8928-4353d9aa13f2.png)

"Select: between |\_\_\_\_\_| and |\_\_\_\_\_|" with the min and the max being optional.

**Comment by tfrancart** [comment]
This is now implemented : http://docs.sparnatural.eu/widgets.html#number-widget
