### ISSUE TITLE
Rendering of documentation

### ISSUE THREAD

**Issue by SteinerPascal** [sparna-git/Sparnatural#455]
Hi @tfrancart,
I just noticed that the rendering of the documentation on the website is not the same as if you open the file on the repo. Some things are not correct:
1. Images are not found on https://github.com/sparna-git/Sparnatural/blob/master/docs/JSON-based-configuration.md
2. the Json example are not showed in a code block on https://github.com/sparna-git/Sparnatural/blob/master/docs/JSON-based-configuration-datasources.md
3. Rendering of JSON in dropdown minimal example in https://docs.sparnatural.eu/JSON-based-configuration.html

**Comment by tfrancart** [comment]
Hi @SteinerPascal 

- fixed the images by providing full link to image URL
- fixed the table structure so that it works with code blocks (see https://gist.github.com/MarcoEidinger/c0f0583f19baca0a8f33bcded644be41)
- Cannot mix backticks inside HTML code; use `<pre lang="json">` instead
