### ISSUE TITLE
Adding Tooltip or title on Reset and Launch buttons

### ISSUE THREAD

**Issue by ethieblin** [sparna-git/Sparnatural#457]
Hello,

Would it be possible to add a tooltip on the Reset ![image](https://user-images.githubusercontent.com/63397169/222404454-158bf3bd-a446-4c6f-9f2b-a6b5f9eccaa5.png)  and Launch  ![image](https://user-images.githubusercontent.com/63397169/222404499-5aa2e333-e766-43ee-8ab6-525800c68898.png) buttons for accessibility ?

Thank you

**Comment by tfrancart** [comment]
It certainly is possible.

**Comment by tfrancart** [comment]
@ethieblin which tooltip messages do you suggest for both buttons (in french and english) ?
