### ISSUE TITLE
Support for very long drop-down lists in query builder

### ISSUE THREAD

**Issue by adrijanik** [sparna-git/Sparnatural#461]
Hi,

Thanks for developing such a great library. 
I came upon an issue while accessing the dropdown options. I tried to look for the element but it wasn't present in the dropdown menu. Querying knowledge graph is bigger than the one in the museum example below and the drop-down options do not contain all options.
<img width="940" alt="image" src="https://user-images.githubusercontent.com/21140501/227530492-8779cdb7-e33e-4330-ac3f-6d1fba1a25c1.png">

I realised upon a closer look at the codebase that when the query is sent to triplestore, the results are limited to 500.  See below:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/21140501/227527597-73d34fd3-4fcb-4850-ad34-46f84afc348f.png">
in file: [SparnaturalConfigDatasources.js](https://github.com/sparna-git/Sparnatural/tree/9d2e5212448f2326929fbac7c82b770350085944/src/sparnatural/ontologies/SparnaturalConfigDatasources.js)
I tweaked a bit the query to remove the limit as I needed to query for items that were not in the list. Initially the problem seemed to be solved for queries with low number of results.
However, sometimes it happens that when there are many more options > 10 000, the drop-down becomes unresponsive, even though the list is populated it is not possible to search the dropdown and the page freezes.

I was wondering if you have any plans to implement handling long drop-down lists in query builder differently and if you could suggest how to navigate around it so the drop-down can support more than 10000 results.
I'd appreciate if you could help me out in here.
Thanks much!

**Comment by tfrancart** [comment]
Hi @adrijanik and thanks for stopping by.
The LIMIT keyword for dropdown lists is on purpose. For larger lists of results the property should be changed to an AutocompleteProperty instead of a ListProperty.
Lists are only suitable for relatively small sets of entities; as you experiences yourself, populating lists with thousands of results is unresponsive and even does not make sense for the user.

So : change your property to an AutocompleteProperty.

**Comment by adrijanik** [comment]
Thanks @tfrancart that sounds just like the solution I need! I will try and update the property to autocomplete.
