### ISSUE TITLE
Pass typePredicate as parameter in datasources queries (?)

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#463]
After fixing #440, the remaining problem is that all included datasources are still using rdf:type as their type predicate. So even when defining the typePredicate parameter, the default datasources won't work.

Probably we need to pass the typePredicate as a parameter to the queries, just like we pass the language parameter.

**Comment by SteinerPascal** [comment]
I thought this should work... Are you working on it?

**Comment by tfrancart** [comment]
Yes I will take care of this, Thanks
