### ISSUE TITLE
Incorrect query generation when unselecting EndClassGroup

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#465]
1. Generate a simple query X --property--> Y = all
2. Change the EndClassGroup to Z, select "all", and click on the eye of "Z" to select it : `X --property--> Z (selected) = all`

The generated SPARQL query is wrong as an extra variable is generated for X:

![image](https://user-images.githubusercontent.com/2728945/229727854-787e4c97-3254-4967-a884-5ae312a3fa48.png)

![image](https://user-images.githubusercontent.com/2728945/229727985-f99b965d-b2b0-44ca-b77f-feb787020b67.png)

here the variable "?Lot_partenaire_4" should not be here

**Comment by tfrancart** [comment]
this comes from the `ActionStore.variables` array

**Comment by tfrancart** [comment]
This can come from the fact that in RemoveEndClass.ts we are recreating the complete CriteriaGroup, which triggers a new variable generation

![image](https://user-images.githubusercontent.com/2728945/229734609-152b29b1-fcb8-4a74-a925-35758a9ec233.png)

**Comment by SteinerPascal** [comment]
Should I have a look at it?

**Comment by tfrancart** [comment]
1. RemoveEndClass empties CriteriaGroup and recreate a completely new one, then reselect the first class based on previous selection
2. The recreation of the StartClassGroup uses a new sequence counter from the `actionStore.sparqlVarID`
3. RemoveEndClass ask to "updateVarList" that should reset `actionStore.variables` based on the actually selected variables in the UI
4. When clicking on the eye, `onSelectViewVar` event is triggered, which calls selectViewVar, then readVariablesFromUI, and this is where the bug is : this returns the extra, unwanted "xxxx_1" variable.

**Comment by tfrancart** [comment]
I think in the updateDraggables function, we just remove the HTML but we don't actually remove the draggable from the list of draggables.
![image](https://user-images.githubusercontent.com/2728945/233080300-c595e22a-e38b-4ced-af7a-2b0a80d6e820.png)
