### ISSUE TITLE
Named graph in configuration

### ISSUE THREAD

**Issue by ethieblin** [sparna-git/Sparnatural#466]
Hello,

I would like to query only a named graph in a SPARQL endpoint.
I did not find such an option in the documentation, is it possible to do so ?

Thanks :)

**Comment by tfrancart** [comment]
Hello @ethieblin 

This is possible by passing the named graph URI as the `default-graph-uri` parameter to the SPARQL endpoint URL, as per https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#dataset

You can use something similar to this as the value of the `endpoint` parameter of `spar-natural` : `https://smt.esante.gouv.fr/api/sparql?default-graph-uri=http%3A%2F%2Fdata.esante.gouv.fr%2Fgraph%2Fterminologie-ref_interop_med`

**Comment by tfrancart** [comment]
See updated documentation for the `endpoint` parameter at http://docs.sparnatural.eu/Javascript-integration#html-attributes-reference
