### ISSUE TITLE
Bug in boolean querying

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#472]
![image](https://user-images.githubusercontent.com/2728945/232787955-6157d94f-f0b5-439f-b940-3b5044c3f11b.png)
(see the double ?? in variable name)

![image](https://user-images.githubusercontent.com/2728945/232788093-a1eb50bd-2ece-4324-8284-314690504f8d.png)

**Comment by Marie-Sparna** [comment]
![image](https://user-images.githubusercontent.com/122270728/232812729-d547d245-ce89-4eb2-8306-8824d1132222.png)

Le filtre true/false n'est pas pris en compte, les résultats de recherche sont faussés
