### ISSUE TITLE
Bug sur dimension des champs de recherche ou listes déroulantes

### ISSUE THREAD

**Issue by Marie-Sparna** [sparna-git/Sparnatural#473]
![image](https://user-images.githubusercontent.com/122270728/232814115-7b4931f3-2a70-4522-b116-027461922009.png)

Après plusieurs requêtes dans un même écran, certains champs de recherche / ou sélecteurs pour les listes déroulantes ne font apparaître qu'un seul caractère.

![image](https://user-images.githubusercontent.com/122270728/232816758-5c323a5c-61e3-49a5-bfa5-5f754da40852.png)

Quand on rafraîchit la page le bug n'est pas reproduit

**Comment by tfrancart** [comment]
Il faudrait que tu donnes une séquence exacte et reproductible pour reproduire ce comportement. Je n'arrive pas à le reproduire sur la démo.

**Comment by Marie-Sparna** [comment]
Bug résolu sur la dernière mise à jour !
