### ISSUE TITLE
sparnatural.clear() function doesn't seem to be callable anymore in 8.2

### ISSUE THREAD

**Issue by Voldenuix** [sparna-git/Sparnatural#493]
I just updated my sparnatural.js with the last 8.2 version.
I was using the function sparnatural.clear() in a event listener but now the event doesn't clear the query as before. 
(see the index.html, line 469)

var graphCheck = document.getElementsByClassName("graphCheck");
graphCheck.change(function(){
		sparnatural.clear();
                yasqe.setValue("");
});
[openart_0.2.zip](https://github.com/sparna-git/Sparnatural/files/11353232/openart_0.2.zip)

**Comment by MrSpitfire06** [comment]
Problem solved nothing to do with the new version.
