### ISSUE TITLE
Conversion SPARQL

### ISSUE THREAD

**Issue by antoine37120** [sparna-git/Sparnatural#5]

**Comment by tfrancart** [comment]
Finalement, lorsqu'on aura sélectionné une valeur, il  ne faudra pas ajouter le critère redondant de type dans la requête générée :

```
SELECT ...
WHERE {
  ?this a :Site .
  ?this :trouve_par <http://toto> .
  <http://toto> a :Person # ne plus ajouter cette ligne redondante
}
```

La requête générée devra donc avec la structure suivante :

```
SELECT ...
WHERE {
  ?this a :Site .
  ?this :trouve_par <http://toto> .
}
```

Penses-tu qu'on puisses contrôler ce comportement par une option dans la config ?

**Comment by antoine37120** [comment]
Contrôler par une option dans la config js (paramètre passer à la fonction insérant le composant) est possible. Je l'introduirai dès que j'annulerai l'ajout du critère redondant.
