### ISSUE TITLE
Changing Easyautocomplete default max length

### ISSUE THREAD

**Issue by ethieblin** [sparna-git/Sparnatural#518]
Hello,

I would like to use the default autocomplete widget, but it sets a default limit to 6.

Is there any way to configure sparnatural to set this limit higher ?

[easyautocomplete configuration](https://github.com/pawelczak/EasyAutocomplete/blob/9bac5160dccae94fd03e2daaf2352556cfbb306b/src/configuration.js#L49)

Thanks :)

**Comment by tfrancart** [comment]
No, that's not possible.
The progression towards SHACL-based configuration may allow to define specific config attributes on UI widgets.
This is similar to e.g. customize map widget starting point (#416)

**Comment by ethieblin** [comment]
Thanks for the answer !

**Comment by tfrancart** [comment]
Closing this. The followup ticket that will deal with this is #548 
The latest version of Sparnatural uses awesomeplete instead of EasyAutocomplete.
