### ISSUE TITLE
vue integartion

### ISSUE THREAD

**Issue by scenaristeur** [sparna-git/Sparnatural#519]
Bonjour Thomas, 

je souhaitais importer sparna dans une appli vue js en utilisant ce code , comme je fais habituellement pour n'importe quel composant vuejs

 example ici https://github.com/scenaristeur/Sparnatural/blob/master/examples/sparna-vue/src/views/HomeView.vue

```
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <SparNatural />
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
// @ is an alias to /src
import HelloWorld from '@/components/HelloWorld.vue'
import SparNatural from 'sparnatural'

export default {
  name: 'HomeView',
  components: {
    HelloWorld,
    SparNatural
  }
}
</script>

```

mais j'ai ce message dans la console du navigateur

[Vue warn]: Component is missing template or render function. 
  at <SparNatural> 
  at <HomeView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

Vuejs a besoin d'un composant html de base <template></template> et de n'avoir qu'un seul élément root dans ce template. 
Je pensais changer BaseClassFectory de la sorte : 

        html = $(`<div class="${baseCssClass}"></div>`);
    }
    **html = $(`<template>${html}</template>`);**
    return html;
  }

mais ça n'a pas l'air de fonctionner... une idée ?

**Comment by tfrancart** [comment]
closed due to inactivity
