### ISSUE TITLE
Enabling prefixed uri to be taken into account when building a query

### ISSUE THREAD

**Issue by PyHahiro** [sparna-git/Sparnatural#520]
Hello, I am facing an issue with sparnatural, using my own endpoint, I can get values that are shortened 
exemple : I have an internal prefix @Prefix ex: http://exemple.com/
and once I get value from my endpoint with the right format 

```json
{
   "rdfterm" : 
   {
      "type": "uri",
      "value" : "ex:test1"
   }
}
```

the sparnatural query builder will construct the following uri :  

> actual :  

`<ex:test1>`

> expected :  

`ex:test1`

Is there a way of having the expected value or not ?

- if not, maybe you could add an other option for types like "prefixedUri"
- Or even add other possible values
```
{
  head: ..,
  result: ..,
  **prefixes**: ..
}

```

**Comment by tfrancart** [comment]
I understand this is an issue in the table result ? then is not Sparnatural, this is YASGUI/YASR. Yasr can take some prefixes as parameters, see https://triply.cc/docs/yasgui-api/#yasr-configuration

**Comment by PyHahiro** [comment]
I am not using yasgui, the problem comes from sparnatural queryUpdated event listener, which build a queryString from the individual selection after clicking on widgets, I have no way to tell sparnatural that it should build the query string with shortened uri

**Comment by tfrancart** [comment]
Are you using the "sparqlString" annotation ? If yes, make sure you only use full URIs, not prefixed ones, included in `<...>`. See http://docs.sparnatural.eu/OWL-based-configuration.html#common-annotations-applicable-to-all-properties, property `core:sparqlString`

**Comment by PyHahiro** [comment]
I don't use annotation but I have tried to create custom sparqlString and it has worked when giving full uri, since I handle specific prefix in my endpoint, I can also use prefixed ones in some case, my issue comes from the results, here is my queryUpdated listener :

```ts
sparnaturalRef?.current?.addEventListener(
      "queryUpdated",
      (event: SparnaturalEvent) => {
        let queryStr = event?.detail?.queryString;
        if (queryStr) {
          onChange(queryStr);
        }
      }
    );
    ```
    
    is there a way for queryUpdated to be like : hey, this uri is a prefixed one and not a full uri, therefore I should not give your prefixed uri <...> when building my event?.detail?.queryString
    
    Or am I misunderstanding something

**Comment by tfrancart** [comment]
I don't understand. Please provide a sample of your configuration file.

**Comment by PyHahiro** [comment]
Ok, I was misunderstanding something about sparnatural and the way it was working with yasgui, since at the time I didn't use yasgui, my issue was with me missing an implementation for what I wanted to achieve, I will close this issue and create one better related to my current issue
