### ISSUE TITLE
Add documentation for how to use Yasgui sparnatural LabelledUriTable 

### ISSUE THREAD

**Issue by PyHahiro** [sparna-git/Sparnatural#524]
So I have been using sparnatural and yasgui together recently in react, and now that I have been able to make it work. I wanted to add some plugin by myself which I find very hard to do but then I realized you already created a plugin named `LabelledUriTable`
https://github.com/sparna-git/Sparnatural-yasgui-plugins.

This may have nothing to do with sparnatural it self, but since both Yasgui and Sparnatural are linked, adding few instructions or redirections could help.

especially in react where sparnatural/yasgui objects differ slighly from their respective documentation.

Thank you in advance and have a nice day

**Comment by SteinerPascal** [comment]
Hey @PyHahiro, Yes you are right the plugin generation has nothing to do with Sparnatural. In fact Sparnatural is strictly segregated from Yasgui (although I admit they go well together). To create plugins for Yasgui i would like to refer at https://triply.cc/docs/yasgui-api/#writing-a-yasr-plugin . There you should find the documentation on how to achieve this. Good luck!

**Comment by tfrancart** [comment]
This is clearly out of scope of Sparnatural, but I reopen to keep track of it as this definitely lacks documentation

**Comment by tfrancart** [comment]
This is now documented at http://docs.sparnatural.eu/YasGUI-plugins.html. If what you are looking is inspiration on how to write a yasGUI plugin, see the source code repository at https://github.com/sparna-git/sparnatural-yasgui-plugins
