### ISSUE TITLE
Test map widget on RiC-O data

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#566]
Data file provided by @florenceclavaud : 
[Exemple_formats_coordonnees.txt](https://github.com/sparna-git/Sparnatural/files/14511027/Exemple_formats_coordonnees.txt)

(1. write RiC-O file, 2. test map widget)

**Comment by florenceclavaud** [comment]
The coordinates are those of the first place described here: [https://github.com/ArchivesNationalesFR/Referentiels/blob/main/lieux/rdf/FRAN_communes_01.rdf](https://github.com/ArchivesNationalesFR/Referentiels/blob/main/lieux/rdf/FRAN_communes_01.rdf) (L'Abergement-Clémenciat (Ain)). We did not release the full version of the file, as the whole dataset would be really huge, but we have the geometries of all French administrative areas, using the format of option 1. And we are also working on Parisian streets. So we would be happy to know if the third option in the txt file is correct (we believe it is) and works with Sparnatural; - in such a case we will fix our datasets. See also [https://github.com/ArchivesNationalesFR/Referentiels/issues/6](https://github.com/ArchivesNationalesFR/Referentiels/issues/6).

**Comment by tfrancart** [comment]
geoJSONLiteral **does** exists : https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#_geojson
I don't see any occurrence of it in GraphDB, so this may not be supported.

**Comment by tfrancart** [comment]
A MULTIPOLYGON in WKT does require 3 parenthesis. There was 2 problems with the data :
- Problem 1 : each pair of lat/long in the data was put in between parenthesis, while they should not :
  - `MULTIPOLYGON(((2.296869638468005 48.8735484315143), (2.2968813746201167 48.87354478436745), ...`  should be instead `MULTIPOLYGON(((2.296869638468005 48.8735484315143, 2.2968813746201167 48.87354478436745,...`
  - Note there is 3 parenthesis at the beginning, but each pair of lat/long is *not* in parenthesis
- Problem 2 : The polygon described should be closed, and *the last pair of lat/long should be a copy of the first pair* :
  - `MULTIPOLYGON((2.296869638468005 48.8735484315143, 2.2968813746201167 48.87354478436745, 2.296882298769853 48.87354601290201, /* snip */, 2.296869638468005 48.8735484315143)))`
  - Note how the very last pair of lat/long is the same as the first one

Here is a working example : 
[test-coordinates-thomas.zip](https://github.com/sparna-git/Sparnatural/files/14521246/test-coordinates-thomas.zip)

I can confirm that Sparnatural map widget works on this test file

**Comment by florenceclavaud** [comment]
OK, thanks a lot @tfrancart! This will allow us to move forward. And it is great to know that Sparnatural will be able to process those data.
I think I also have found the spec where all this is defined, with [examples](https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html#C.1.1.3.1) - which we were missing in fact.
@MZrhal, you can move on with the Parisian streets now, and we will work on the other places later on.
