### ISSUE TITLE
Map widget : when a query is loaded, if I edit the value the area does not appear on the Map

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#583]
Testes à https://sparnatural.eu/demos/demo-nakala/ - en chargeant la query d'exemple "Du côté de la côte d'Azur et du Piémont", puis en essayant de ré-éditer le critère de position

**Comment by antoine37120** [comment]
@tfrancart C'est fixé, il y avait 2 noms de propriété différents utilisés pour stocker la valeur du widget. Mergé en une seule.
