### ISSUE TITLE
CORS doesn't need to be deactivated in newer Firefox versions

### ISSUE THREAD

**Issue by marimeireles** [sparna-git/Sparnatural#588]
One doesn't seem to need to deactivate CORS in Firefox anymore 125.0.3 (64-bit).
Might be worth to add a note in the docs.

**Comment by tfrancart** [comment]
Are you referring to the chapter "Allow loading of local files in your browser" in the "hello sparnatural" doc ?
Please provide evidence of this with a pointer to a release note or an article explaining this. Thanks
