### ISSUE TITLE
SHACL config: property paths and blank nodes

### ISSUE THREAD

**Issue by CFGrote** [sparna-git/Sparnatural#603]
In the wake of #602, I now observe the following behaviour:

My shacl config;
```
...

shapes:SO_0000316 rdf:type owl:NamedIndividual ,
    sh:NodeShape ;
    rdfs:label "CDS"@en ;
    rdfs:comment "Coding DNA Sequence"@en ;
    sh:property shapes:SIO_001166 ;                      # annotation
    sh:targetClass <http://purl.obolibrary.org/obo/SO_0000316> ;
    volipi:iconName "fa-solid fa-dna" .

shapes:SIO_001166
    sh:name      "annotation"@en ;
    sh:node       shapes:Go_term ;
    sh:path      (<http://semanticscience.org/resource/SIO_001166> <http://www.w3.org/ns/hydra/core#member>) .

shapes:GO_term rdf:type sh:NodeShape , owl:NamedIndividual ;
    sh:name "Go annotation" ;
    sh:nodeKind sh:Literal ; 
    volipi:iconName "fa-solid fa-gopuram" ;
    sh:property shapes:name , shapes:data_2091 , shapes:IAO_0000115 .

shapes:name
    sh:maxCount  1 ;
    sh:minCount  1 ;
    sh:name      "name"@en ;
    sh:path      <https://schema.org/name> .

shapes:data_2091
    sh:maxCount  1 ;
    sh:minCount  1 ;
    sh:name      "ID"@en ;
    sh:path      <http://edamontology.org/data_2091> .

shapes:IAO_0000115
    sh:name "definition"@en ;
    sh:path obo:IAO_0000115 .
```
Explanation:

Property shape `shapes:SIO_001166` relates NodeShape `shapes:SO_0000316` to NodeShape `shapes:GO_term` via a two part property path. The `sh:targetClass` of `shapes:GO_term` is undefined (actually a BlankNode).

The problem is that the generated sparql query contains a `?GO_term rdf:type shapes:GO_term .` clause, which is not matched in the queried graph since the targeted object is a BN. Previously, I was able to fix this kind of problem through the `nodeKind sh:Literal` property on the NodeShape. Am I doing it wrong here or is it a problem related to the multipart property path?

Screenshot:
![image](https://github.com/sparna-git/Sparnatural/assets/15476807/9c77817f-d69d-4546-8e9f-022007772985)

Removing line 5 from the query then produces the expected results:
![image](https://github.com/sparna-git/Sparnatural/assets/15476807/c98ecf7f-01b0-430d-8adb-aad94f2f55e6)

**Comment by tfrancart** [comment]
I confirm the issue. Nothing to do with the property path.
Something weird is going on with n3store, maybe a dependency upgrade issue.

**Comment by tfrancart** [comment]
The config is buggy. You have

```turtle
shapes:SIO_001166
    sh:name      "annotation"@en ;
    sh:node       shapes:Go_term ;
```

(lowercase "o" in "Go_term")

but you have


```turtle
shapes:GO_term rdf:type sh:NodeShape , owl:NamedIndividual ;
```

(uppercase "O" in GO_term)

**Comment by CFGrote** [comment]
Thanks for catching @tfrancart . That seems to solve it.
