### ISSUE TITLE
Help needed: shacl config for federated queries

### ISSUE THREAD

**Issue by CFGrote** [sparna-git/Sparnatural#604]
I need help configuring federated queries with shacl. I got it to work in owl, following the documented examples. Copying over the relevant parts from owl to shacl does not work. Is it not (yet?) supported or can someone list the required steps?

Thanks in advance!

**Comment by tfrancart** [comment]
Theoretically, it is exactly equivalent to using an OWL property, except you start with a property shape. I never really tested it recently with a SHACL config. You need to:

1. Add a `http://data.sparna.fr/ontologies/sparnatural-config-core#sparqlService` annotation on a property shape that is to be executed as a SERVICE
2. This annotation will point to an entity that itself is the subject of an `http://www.w3.org/ns/sparql-service-description#endpoint` predicate holding the actual SPARQL endpoint URL
3. Optionnaly you can add  ̀http://data.sparna.fr/ontologies/sparnatural-config-core#executedAfter` on the property shape to force the rest of the query to be put in subquery that will be evalued before the SERVICE clause is sent

**Comment by CFGrote** [comment]
thanks, that seems to do it. Should become part of the documentation.

**Comment by tfrancart** [comment]
Definitely needs documentation, I keep the issue open

**Comment by tfrancart** [comment]
See http://docs.sparnatural.eu/Federated-querying.html#configuration-in-shacl
