### ISSUE TITLE
Labels not fetched in query

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#609]
This query underlies a label fetcher:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?uri ?label WHERE {
  ?domain rdf:type <http://www.graceful17.org/ontology/institution>;
    <http://www.graceful17.org/ontology/primary_place> ?uri.
  ?uri rdfs:label ?label.
  FILTER(((LANG(?label)) = "") || ((LANG(?label)) = "en"))
  FILTER(ISIRI(?uri))
}
ORDER BY (UCASE(?label))
LIMIT 500
```

The query works fine in the [endpoint](https://dataria.org/sparql/#query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20DISTINCT%20%3Furi%20%3Flabel%20WHERE%20%7B%0A%20%20%3Fdomain%20rdf%3Atype%20%3Chttp%3A%2F%2Fwww.graceful17.org%2Fontology%2Finstitution%3E%3B%0A%20%20%20%20%3Chttp%3A%2F%2Fwww.graceful17.org%2Fontology%2Fprimary_place%3E%20%3Furi.%0A%20%20%3Furi%20rdfs%3Alabel%20%3Flabel.%0A%20%20FILTER(((LANG(%3Flabel))%20%3D%20%22%22)%20%7C%7C%20((LANG(%3Flabel))%20%3D%20%22en%22))%0A%20%20FILTER(ISIRI(%3Furi))%0A%7D%0AORDER%20BY%20(UCASE(%3Flabel))%0ALIMIT%20500&endpoint=https%3A%2F%2Fdataria.org%2Fsparql%2Fquery&requestMethod=POST&tabTitle=Query%203&headers=%7B%7D&contentTypeConstruct=application%2Fn-triples%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table) and the YASGUI widget.

However, the List is not filled:

![grafik](https://github.com/user-attachments/assets/0976dd9d-ae39-476f-a011-8e7d4be88cf4)

It works with the inverse (as ^)...

Check out https://dataria.org/ask

Do you have any clue why that is?

**Comment by ch-sander** [comment]
Seems like a Browser or Cache issue. Sorry.

![grafik](https://github.com/user-attachments/assets/cd8afbf8-25b7-46f1-babe-d6a3ea8fe008)

**Comment by tfrancart** [comment]
There is indeed some browser-side caching implemented in Sparnatural. Make sure to check your browser console to see whether a certain HTTP query result is read from cache or actually sent to the server. See the parameter localCacheDataTtl : http://docs.sparnatural.eu/Javascript-integration.html#html-attributes-reference
