### ISSUE TITLE
No OPTIONAL for fetching labels  

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#610]
The default labels are fetched by, e.g., `OPTIONAL { ?event_6 rdfs:label ?event_6_label. }`.

Is it possible to switch off the OPTIONAL (if the query is built by the widget)? My queries tend to time out because of these optionals and my resources all have a rdsf:label.

**Comment by ch-sander** [comment]
see also https://github.com/oxigraph/oxigraph/issues/954

**Comment by tfrancart** [comment]
Yes, on the property that you configure as the default label, do *NOT* set the core:enableOptional flag to true. Then Sparnatural will not use the OPTIONAL keyword to fetch them. See http://docs.sparnatural.eu/how-to-configure/How-to-configure-Sparnatural.html#_kmiilevbt32l (this is similar if you use a SHACL-based config)

**Comment by ch-sander** [comment]
Ah, great and very thoughful configuration!

**Comment by ch-sander** [comment]
I did not configure the `rdfs:label` property at all for sparnatural. So, if not specified the `enableOptional` flag will be set to true by default?

**Comment by tfrancart** [comment]
No is is false by default. Can you share your config ?

**Comment by ch-sander** [comment]
https://dataria.org/file/results/config.ttl

**Comment by ch-sander** [comment]
I think I have set a global variable in a central place in the JavaScript. I will check that. Not remembering where...

**Comment by tfrancart** [comment]
I was wrong. If not set explicitely to false, then the enableOptional flag is true. Hence the behavior you see.
Note that the defaultLabelProperty can point to another URI representing a property in your config, itself mapped to rdfs:label using core:sparqlString annotation.

If you are proficient with SHACL, I suggest you move from OWL config to SHACL config : http://docs.sparnatural.eu/SHACL-based-configuration.html
