### ISSUE TITLE
AND selector glitch

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#611]
as seen in the screenshots the control to add an "AND" to the subject of a triple appears in place where it shouldn't.

Not an issue but I wonder if this is an easy fix

![grafik](https://github.com/user-attachments/assets/33b48b4e-c70e-45e0-9dfb-353883ccd105)
![grafik](https://github.com/user-attachments/assets/b096361a-a048-452b-b901-1598da15a3fa)

**Comment by tfrancart** [comment]
have you resized your window somehow after Sparnatural was first loaded ?
Never saw that, but there are some AND-positioning related issues : https://github.com/sparna-git/Sparnatural/issues/544

**Comment by ch-sander** [comment]
Now, but working in a vertical monitor setup. Sometimes, my sad experience, the best responsive frontend fail to fully adjust.

I will test it further and report back

**Comment by ch-sander** [comment]
I confirm this to happen both in firefox and chrome. Maybe it's due to the rendering as flask template? Or a conflict with another bootstrap library loaded?

**Comment by ch-sander** [comment]
Maybe related to #544

**Comment by ch-sander** [comment]
Also "Where" is floating around, sadly
![grafik](https://github.com/user-attachments/assets/c04dc553-9a70-4b5c-930f-8bc98aec50c5)

**Comment by ch-sander** [comment]
It's due to a conflict between bootstrap v4 and v5 CSS -- nothing related to sparnatural
