### ISSUE TITLE
prefixes (unstable) as JSON Object

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#620]
prefixes (unstable) at https://docs.sparnatural.eu/Javascript-integration.html#html-attributes-reference

I imagine the space after the colon is just a typo (or doesn't matter) in the example: `foaf: http://xmlns.com/foaf/0.1/ skos:http://www.w3.org/2004/02/skos/core#`

However, I was wondering what is unstable here and if it was possible to pass a JSON object, e.g. `@ context` like in JSON-LD, instead of this string. Would make integration more robust.

**Comment by tfrancart** [comment]
> I imagine the space after the colon is just a typo (or doesn't matter)

shouldn't matter

> However, I was wondering what is unstable here

This is less and less unstable. It triggers additionnal reparsing of the SPARQL query strings (final one and the ones in the list / autocomplete)

> it was possible to pass a JSON object

No. Passing JSON objects inside HTML attributes is ugly. 
RDFa prefix syntax is identical: https://www.w3.org/TR/rdfa-core/#examples

**Comment by ch-sander** [comment]
Why isn't the query bound to prefixes with such config

```html
<spar-natural 
            src="[/static/sparnatural/config.ttl](view-source:https://dataria.org/static/sparnatural/config.ttl)"           
            endpoint="https://g17dev.dhi-roma.it/sparql"
            lang="en"
            defaultLang="en"
            distinct="true"
            limit="10000"
            debug="true"
            prefixes="grace:http://www.graceful17.org/ontology/ g17:http://www.graceful17.org/resources/ "
        ></spar-natural>
```

The sparql will still be [rendered](https://dataria.org/ask#query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0ASELECT%20DISTINCT%20%3Farchive_1%20%3Farchive_1_label%20%3FGIS_2%20%3FGIS_2_label%20WHERE%20%7B%0A%20%20%3Farchive_1%20rdf%3Atype%20%3Chttp%3A%2F%2Fwww.graceful17.org%2Fontology%2Farchive%3E%3B%0A%20%20%20%20%3Chttp%3A%2F%2Fwww.graceful17.org%2Fontology%2Fcalled%3E%20%3Farchive_1_label%3B%0A%20%20%20%20%3Chttp%3A%2F%2Fwww.graceful17.org%2Fontology%2Fwkt%3E%20%3FGIS_2.%0A%7D%0ALIMIT%2010000) like

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?archive_1 ?archive_1_label ?GIS_2 ?GIS_2_label WHERE {
  ?archive_1 rdf:type <http://www.graceful17.org/ontology/archive>;
    <http://www.graceful17.org/ontology/called> ?archive_1_label;
    <http://www.graceful17.org/ontology/wkt> ?GIS_2.
}
LIMIT 10000
```

I must be missing something here...sorry!

**Comment by tfrancart** [comment]
Probably because you have https in your prefixes but http in your query :-)

**Comment by ch-sander** [comment]
At the risk of embarrassing myself even more: I don't see `https` (only in the query endpoint but this cannot be it).

**Comment by ch-sander** [comment]
@tfrancart sorry to be in your neck with this, but you have any idea why it won't work (#637 and #587)?
