### ISSUE TITLE
No " volipi:iconName column" in the sample sparnatural-car-configuration-shacl.xlsx

### ISSUE THREAD

**Issue by lubianat** [sparna-git/Sparnatural#626]
Hi!

I am back to using Sparnatural after 2 years and doing some migrations from OWL to SHACL. 

In the example file at http://docs.sparnatural.eu/how-to-configure-shacl/How-to-configure-Sparnatural-shacl.html

it says that: 

--
the `volipi:iconName` column is where you can copy-paste the code of a [Font Awesome free icon](https://fontawesome.com/search?o=r&m=free) you will choose on the website (e.g. “fa-solid fa-car”).
--

I did not see this column when scrolling: 

![image](https://github.com/user-attachments/assets/b6df58a6-9910-480b-b564-b61b8738bb6a)

Am I missing something? 

I imagine I could add a new colum with the _volipi:iconName_ header, but I wanted to double check anyways. 

Thanks again for the amazing software (and for all the upgrades from 7.0 --> 9.5)

**Comment by tfrancart** [comment]
The column is hidden in the saved version of the file. It is column C. Make sure you un-hide all columns.

**Comment by lubianat** [comment]
Thanks!
