### ISSUE TITLE
How can I have a label property working for multiple different entity kinds?

### ISSUE THREAD

**Issue by lubianat** [sparna-git/Sparnatural#634]
Hello, 

I am exploring the new features with config generation, the SHACLS config workflow looks really good! 

So, I have a configuration table (https://docs.google.com/spreadsheets/d/1EsUh-qZP4_VGJoucT8shlT3YfB_Tgyug/edit?gid=629114015#gid=629114015) and I am trying to find a way to add labels to my entities. 

The deal is  I have 36 entity kinds, and all of them use `rdfs:label` as the relation for labels. Is there any way on the SHACL config workflow to set a single line on Properties to work for multiple domains? 

e.g. something that instead of 

^sh:property(separator=",")
--
this:Disease
this:Pharmaceutical_Product

would be something like 

^sh:property(separator=",")
--
this:Disease & this:Pharmaceutical_Product

or do we need to have a single line for each entity kind, duplicating all the details?

**Comment by lubianat** [comment]
Thanks again for the awesome product!

**Comment by tfrancart** [comment]
> The deal is I have 36 entity kinds, and all of them use rdfs:label as the relation for labels. Is there any way on the SHACL config workflow to set a single line on Properties to work for multiple domains?

Yes, simply list all the node shapes identifiers in the `^sh:property(separator=",")` column, separated by a comma. This is what the `separator=","` parameter is here for. So, in your case : `this:Disease, this:Pharmaceutical_Product`.

This is documented in an advanced note at https://docs.sparnatural.eu/how-to-configure-shacl/How-to-configure-Sparnatural-shacl.html#declare-simple-properties:

![image](https://github.com/user-attachments/assets/588e992c-0867-448a-9371-4e4d9f1c3260)

**Comment by lubianat** [comment]
oh, wow, obviously. Thank you very much!

**Comment by lubianat** [comment]
@tfrancart a continuation question: 

In this case, is there a way from blocking the domain of appearing as a selectable subject in Sparnatural? 


E.g., my only property with "Disease" in the domain is the label property. By setting sh:deactivated^^xsd:boolean to TRUE I get it not to show up, but the "Disease" is now a selectable option with no associated properties: 


![image](https://github.com/user-attachments/assets/fbf4c560-ed53-4172-a662-3b633d36e99a)

**Comment by tfrancart** [comment]
Hmmm that's a bug. Normally the "Disease" class should not show up if it has only deactivated properties. let me have a look.

**Comment by tfrancart** [comment]
I confirm this is a bug - or rather something that was not implemented. This is fixed but in the meantime I suggest you mark your Disease class itself with sh:deactivated true, this will hide it from the initial list of classes.

**Comment by tfrancart** [comment]
This is fixed in #635

**Comment by lubianat** [comment]
Thanks!
