### ISSUE TITLE
Entity with a long label : only "..." are displayed in the arrow

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#638]
Je sélectionne une entité dont le libellé est "Quartier, paroisse ou arrondissement de Paris":

![image](https://github.com/user-attachments/assets/7ae08961-493c-42c2-971b-f1394f47754e)

C'est seulement "..." qui s'affichent ensuite dans la flèche:

![image](https://github.com/user-attachments/assets/2ed46c84-49f1-4ec8-80e5-e75731be8d3c)

**Comment by antoine37120** [comment]
@tfrancart peux tu me transmettre une config qui permette de reproduire ce bug ?

**Comment by antoine37120** [comment]
@thomas, tu peux tester, correction publiée. L'erreur était que le text-overflow n'était pas appliqué sur la balise du label mais sur son parent.
