### ISSUE TITLE
`rdf:type` gone in new release?

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#641]
when using the recent `sparnatural.js` (https://github.com/sparna-git/Sparnatural/releases/tag/9.5.2) and `sparnatural.js.map` all `rdf:type` predicates are gone, causing a timeout (see https://github.com/epoz/shmarql/issues/25)

### This has been my query until now:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT (COUNT(DISTINCT ?object_8) AS ?object_8_count) ?place_4_label ?place_4 WHERE {
  ?place_1 rdf:type <http://www.graceful17.org/ontology/place>;
    (<http://www.graceful17.org/ontology/falls_within>+) ?place_4.
  ?place_4 rdf:type <http://www.graceful17.org/ontology/place>;
    <http://www.graceful17.org/ontology/called> ?place_4_label;
    <http://www.graceful17.org/ontology/has_main_type> <http://www.graceful17.org/resources/type_77>.
  ?place_1 ^<http://www.graceful17.org/ontology/primary_place> ?institution_6.
  ?institution_6 rdf:type <http://www.graceful17.org/ontology/institution>;
    <http://www.graceful17.org/ontology/holds_immaterial_object> ?object_8.
  ?object_8 rdf:type <http://www.graceful17.org/ontology/object>;
    <http://www.graceful17.org/ontology/called> ?object_8_label;
    <http://www.graceful17.org/ontology/has_main_type> <http://www.graceful17.org/resources/type_460>.
}
GROUP BY ?place_4 ?place_4_label
ORDER BY DESC (?object_8_count)
LIMIT 10000
```

### And now is:

```sparql
SELECT DISTINCT (COUNT(DISTINCT ?object_8) AS ?object_8_count) ?place_4 ?place_4_label WHERE {
  ?place_1 (<http://www.graceful17.org/ontology/falls_within>+) ?place_4.
  ?place_4 <http://www.graceful17.org/ontology/called> ?place_4_label;
    <http://www.graceful17.org/ontology/has_main_type> <http://www.graceful17.org/resources/type_77>.
  ?place_1 ^<http://www.graceful17.org/ontology/primary_place> ?institution_6.
  ?institution_6 <http://www.graceful17.org/ontology/holds_immaterial_object> ?object_8.
  ?object_8 <http://www.graceful17.org/ontology/called> ?object_8_label;
    <http://www.graceful17.org/ontology/has_main_type> <http://www.graceful17.org/resources/type_460>.
}
GROUP BY ?place_4 ?place_4_label
ORDER BY DESC (?object_8_count)
LIMIT 10000
```

I guess this is not intended behavior?

`typePredicate` is not set in the config in `index.html`

### My main.js

```js
// reference to the sparnatural webcomponent
const sparnatural = document.querySelector("spar-natural");

// display on the page the endpoint URL with which sparnatural is configured
document.querySelector("#displayEndpoint").setAttribute("href", sparnatural.getAttribute("endpoint"));
document.querySelector("#displayEndpoint").textContent = sparnatural.getAttribute("endpoint");

// init yasQE query editor
const yasqe = new Yasqe(document.getElementById("yasqe"), {
	requestConfig: {
	  // make sure the endpoint is the same as sparnatural
	  endpoint: sparnatural.getAttribute("endpoint"),
	  method: "GET",
	  header: {}
	},
	copyEndpointOnNewTab: false  
});

// init yasR result display
// register a specific plugin that is capable of displaying clikable label + URI
Yasr.registerPlugin("LabelledUriTable",SparnaturalYasguiPlugins_small.TableX);
Yasr.registerPlugin("Map", SparnaturalYasguiPlugins.MapPlugin);
Yasr.registerPlugin("GridPlugin", SparnaturalYasguiPlugins.GridPlugin);
Yasr.registerPlugin("StatsPlugin", SparnaturalYasguiPlugins.StatsPlugin);
Yasr.registerPlugin("Response", SparnaturalYasguiPlugins.Response);
delete Yasr.plugins['table'];



const yasr = new Yasr(document.getElementById("yasr"), {
	pluginOrder: ["LabelledUriTable", "Response", "Map", "GridPlugin", "StatsPlugin", "response"],
	defaultPlugin: "LabelledUriTable"
});

// link yasqe and yasr
yasqe.on("queryResponse", function(_yasqe, response, duration) {
	yasr.setResponse(response, duration);
	// when response is received, enable the button
	sparnatural.enablePlayBtn();
});

// listener when sparnatural updates the query
// see http://docs.sparnatural.eu/Javascript-integration.html#sparnatural-events
sparnatural.addEventListener("queryUpdated", (event) => {
	// get the SPARQL query string, and pass it to yasQE
	queryString = sparnatural.expandSparql(event.detail.queryString);
	yasqe.setValue(queryString);
	// display the JSON query on the console
	console.log("Sparnatural JSON query structure:");
	console.dir(event.detail.queryJson);
});

// listener when the sparnatural submit button is clicked
// see http://docs.sparnatural.eu/Javascript-integration.html#sparnatural-events
sparnatural.addEventListener("submit", (event) => {
	// enable loader on button
	sparnatural.disablePlayBtn() ; 
	// trigger the query from YasQE
	yasqe.query();
});

// listener when the sparnatural reset button is clicked
// see http://docs.sparnatural.eu/Javascript-integration.html#sparnatural-events
sparnatural.addEventListener("reset", (event) => {
	// empties the SPARQL query on yasQE
	yasqe.setValue("");
});

// hide/show yasQE
document.getElementById('sparql-toggle').onclick = function() {
	if(document.getElementById('yasqe').style.display == 'none') {
	  document.getElementById('yasqe').style.display = 'block';
	  yasqe.setValue(yasqe.getValue());
	  yasqe.refresh();
	} else {
	  document.getElementById('yasqe').style.display = 'none';
	}
	return false;        
} ;

// binds Sparnatural with the YasR plugins
bindSparnaturalWithYasrPlugins(sparnatural, yasr);
// binds Sparnatural with itself for the query execution and integration with yasqe and yasr
bindSparnaturalWithItself(sparnatural, yasqe, yasr);
```

**Comment by tfrancart** [comment]
What's your config like ? OWL or SHACL ? This would be related to the config, not to the JS integration.
Any error in the console ?
What do you get when using the latest (although unstable) 10.0.0-beta : https://github.com/sparna-git/Sparnatural/releases/tag/10.0.0-beta

**Comment by ch-sander** [comment]
OWL: https://dataria.org/file/results/rdf/ontology_sparnatural_20241007.ttl

No console error. Object in console:

```json
[
  {
    "line": {
      "s": "archive_1",
      "p": "http://www.graceful17.org/ontology/holds_source",
      "o": "source_2",
      "sType": "http://www.graceful17.org/ontology/archive",
      "oType": "http://www.graceful17.org/ontology/source",
      "values": []
    },
    "children": []
  }
]
```

Will test v10 immediately

**Comment by ch-sander** [comment]
10.0.0-beta leads to the same issue, it seems. Still no console log that is warning/error. Also, fa-icons are gone but I only replaced css, map and js files for testing

**Comment by ch-sander** [comment]
maybe the syntactic sugar `a` is just not parsed from the OWL?

**Comment by tfrancart** [comment]
Then my advice is : stay with 9.5.1 with your OWL config (if 9.5.1 works), or transition your config to SHACL (which I would strongly suggest). See https://docs.sparnatural.eu/how-to-configure-shacl/How-to-configure-Sparnatural-shacl.html
Here you will find a few SPARQL queries (migration-owl2shacl-xxxx.rq) that can help you extract the classes, properties, datasources and queries from your OWL config and fill-in the SHACL configuration table : https://github.com/sparna-git/Sparnatural/tree/master/docs/how-to-configure-shacl

A lot of new features will use the SHACL-based config

**Comment by ch-sander** [comment]
Hm, alright. OWL really has the advantage of being useful anyway in the semantic data context. I'd be sad to see OWL being deprecated for the config.

My OWL config is dynamically generated from another database tool that exposes JSON-LD (my parser). I imagine simply using the SHACL namespace will then create a valid sparnatural config.ttl -- is that right? It's not mandatory to use the spreadsheet, right?

**Comment by tfrancart** [comment]
No it's not mandatory to use the spreadsheet.
Semantically, the config of Sparnatural is closer to a SHACL spec than to an OWL config. We used OWL simply to benefit from Protégé, but semantically this is a hack.

**Comment by ch-sander** [comment]
Not using Protégé myself, just JSON-LD. I will use [this](http://docs.sparnatural.eu/how-to-configure-shacl/sparnatural-car-configuration-shacl.ttl) as a use case template.

**Comment by ch-sander** [comment]
Hi @tfrancart 
Would you mind taking a brief look at [my first SHACL trial](https://dataria.org/file/results/rdf/shacl_20241010.ttl)? I never worked with it before...
Sparnatural loads but ignores e.g. the search widgets and renders predefined properties (Text, Other,...). Most importantly, it fails to produce SPARQL although the JSON object for the query looks okay.
I get: 

```yaml
Uncaught TypeError: t.getQuads(...)[0] is undefined
    pathToSparql SHACLSpecificationProvider.ts:381
    expandSparql SHACLSpecificationProvider.ts:218
    expandSparql SHACLSpecificationProvider.ts:215
    expandSparql SparnaturalElement.ts:140
    bindSparnaturalWithItself sparnatural-bindings.js:80
    fireQueryUpdatedEvent GenerateQuery.ts:84
    generateQuery GenerateQuery.ts:74
    fo ActionStore.ts:52
    nn CompleteGrpInput.ts:18
    sn GroupWrapperEventStore.ts:22
    yi EndClassWidgetGroup.ts:174
    renderWidgetVal EndClassWidgetGroup.ts:141
    Vi CriteriaGroup.ts:145
    onSelectAll EditComponents.ts:114
    yr EditComponents.ts:100
    sr WidgetWrapper.ts:84
    jQuery 2
SHACLSpecificationProvider.ts:381:63
```

You may test with this public endpoint: https://g17dev.dhi-roma.it/sparql

**Comment by tfrancart** [comment]
- Your `dash` namespace is wrong. It should be `http://datashapes.org/`
- The error could indicate that you have a PropertyShape without an `sh:path`. Could that be the case ? this would not be valid SHACL. On which property does this error appear ?

**Comment by tfrancart** [comment]
Also, you have a problem with `sh:or`. `sh:or` must always be a valid RDF list.
So:
- don't use sh:or when you don't have to.

Instead of this:

```turtle
g17sn:place_name a sh:PropertyShape ;
    rdfs:label "place name"@en ;
    volipi:message "Tooltip for place name" ;
    sh:name "place name" ;
    sh:or [ sh:datatype xsd:string ;
            sh:nodeKind sh:Literal ] ;
    sh:path grace:place_name ;
    dash:searchWidget sparnatural:SearchProperty .
```

You should have this:

```turtle
g17sn:place_name a sh:PropertyShape ;
    rdfs:label "place name"@en ;
    volipi:message "Tooltip for place name" ;
    sh:name "place name" ;
    sh:datatype xsd:string ;
    sh:nodeKind sh:Literal ;
    sh:path grace:place_name ;
    dash:searchWidget sparnatural:SearchProperty .
```

- When you have to, use it this way:

```turtle
    sh:or [ sh:node g17sn:object ],
        [ sh:node g17sn:event ] ;
```

should be

```turtle
    sh:or ( [ sh:node g17sn:object ],
        [ sh:node g17sn:event ]  );
```

**Comment by tfrancart** [comment]
Tip : try to submit your SHACL to https://shacl-play.sparna.fr/play/doc to see if the documentation can be generated. You can even ask it form UML-like diagrams.

**Comment by ch-sander** [comment]
> Tip : try to submit your SHACL to https://shacl-play.sparna.fr/play/doc to see if the documentation can be generated. You can even ask it form UML-like diagrams.

https://shacl-play.sparna.fr/play/doc?format=html&url=https%3A%2F%2Fdataria.org%2Ffile%2Fresults%2Frdf%2Fshacl_20241010.ttl&includeDiagram=true&hideProperties=false

This seems to work. I'll test Sparnatural now.

I'm very grateful for your support!!

**Comment by tfrancart** [comment]
- You cannot have 2 values for sh:class. Otherwise in SHACL semantics it means the value is required to have **both** classes. If you have 2 values, this means you need an sh:or.
- 
So actually this:

```
g17sn:dedication_of a sh:PropertyShape ;
    rdfs:label "dedication of"@en ;
    volipi:message "Tooltip for dedication of" ;
    dash:searchWidget sparnatural:AutocompleteProperty ;
    sh:class grace:institution,
        grace:object ;
    sh:name "dedication of" ;
    sh:nodeKind sh:IRI ;
    sh:or ( [ sh:node g17sn:institution ] [ sh:node g17sn:object ] ) ;
    sh:path grace:dedication_of .
```

Should rather be that (without sh:class):

```
g17sn:dedication_of a sh:PropertyShape ;
    rdfs:label "dedication of"@en ;
    volipi:message "Tooltip for dedication of" ;
    dash:searchWidget sparnatural:AutocompleteProperty ;
    sh:name "dedication of" ;
    sh:nodeKind sh:IRI ;
    sh:or ( [ sh:node g17sn:institution ] [ sh:node g17sn:object ] ) ;
    sh:path grace:dedication_of .
```

or, since your NodeShapes are also classes, you could use `sh:or ( [ sh:class g17sn:institution ] [ sh:class g17sn:object ] ) ;`

**Comment by ch-sander** [comment]
I think I worked it out, mostly!

https://dataria.org/ask

https://shacl-play.sparna.fr/play/doc?format=html&url=https%3A%2F%2Fdataria.org%2Ffile%2Fresults%2Frdf%2Fshacl_20241010.ttl&includeDiagram=true&hideProperties=false

A few questions remain (and more probably will come up in the next days):

1. Is there a setting to disable the "Other" datatype fall-back? Or do I need to confine my SHACL?
2. fa-icons in the grid view don't work yet or my fault?
3. I really like the hierarchical browser, but I tried to deactivate my "anything" root class with the sh property to show its children in the first landing dropdown. Did I miss something? I had my anything class as domain/range for several properties and I use its shacl sibling for global settings, that's why I don't want to cut this class out of the config.
4. I needed to change my config for start/end of dates, not sure if this was due to v10

**Comment by tfrancart** [comment]
> 1. Is there a setting to disable the "Other" datatype fall-back? Or do I need to confine my SHACL?

No. You need to configure your SHACL. See that section of the doc : https://docs.sparnatural.eu/how-to-configure-shacl/How-to-configure-Sparnatural-shacl.html#_Toc26

> 2. fa-icons in the grid view don't work yet or my fault?

Use latest release of yasgui-plugins, this should fix it: https://github.com/sparna-git/Sparnatural-yasgui-plugins/releases/tag/2.0.1

> 3. I really like the hierarchical browser, but I tried to deactivate my "anything" root class with the sh property to show its children in the first landing dropdown. Did I miss something? I had my anything class as domain/range for several properties and I use its shacl sibling for global settings, that's why I don't want to cut this class out of the config.

If I understand correctly, you want to benefit from properties inheritance but you want to hide the shape. I don't hink that is currently possible. Note that instead of using inheritance, you could refer to the **same property shape** from multiple NodeShapes, so that the properties are shared.

> 4. I needed to change my config for start/end of dates, not sure if this was due to v10

I don't understand

**Comment by tfrancart** [comment]
And congratulations for you SHACL config.
You are using some structure of sh:or that the documentation generator does not properly support I think. Make sure your sh:or work as expected in Sparnatural.

**Comment by ch-sander** [comment]
thanks @tfrancart !
> > 3. I really like the hierarchical browser, but I tried to deactivate my "anything" root class with the sh property to show its children in the first landing dropdown. Did I miss something? I had my anything class as domain/range for several properties and I use its shacl sibling for global settings, that's why I don't want to cut this class out of the config.
> 
> If I understand correctly, you want to benefit from properties inheritance but you want to hide the shape. I don't hink that is currently possible. Note that instead of using inheritance, you could refer to the **same property shape** from multiple NodeShapes, so that the properties are shared.

Good idea but will be difficult for my own parser that creates the SHACL from a database. I would need to make an exception for the creation of the root node "anything" in that way, but I'll find a way. Just wanted to make sure it's not simply about `sh:deactivated`.

> 
> > 4. I needed to change my config for start/end of dates, not sure if this was due to v10
> 
> I don't understand

Yes, sorry, I was referring to http://docs.sparnatural.eu/Querying-date-ranges.html. The way it worked in my OWL config didn't quite work out in SHACL but I might be wrong. Just wanted to report. No action needed :).

**Comment by tfrancart** [comment]
> Yes, sorry, I was referring to http://docs.sparnatural.eu/Querying-date-ranges.html. The way it worked in my OWL config didn't quite work out in SHACL but I might be wrong. Just wanted to report. No action needed :).

This has been fixed very recently, but not released yet: https://github.com/sparna-git/Sparnatural/issues/645

**Comment by tfrancart** [comment]
closing this one, feel free to reopen separate issues if needed

**Comment by ch-sander** [comment]
> closing this one, feel free to reopen separate issues if needed

I moved to SHACL for good, unlikely to test the OWL config in future releases.
