### ISSUE TITLE
CONCAT labels in aggregation

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#648]
It seems the aggregator currently does not aggregate the labels of an aggregation:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?place_1 ?place_1_label ?number_2 (GROUP_CONCAT(DISTINCT ?place_12; SEPARATOR = " ") AS ?place_12_group_concat) WHERE {
  ?place_1 rdf:type <http://www.graceful17.org/ontology/place>;
    <http://www.graceful17.org/ontology/called> ?place_1_label;
    <http://www.graceful17.org/ontology/ninox_id> ?number_2;
    (<http://www.graceful17.org/ontology/contains>*) ?place_12.
  ?place_12 rdf:type <http://www.graceful17.org/ontology/place>;
    <http://www.graceful17.org/ontology/called> ?place_12_label.
}
GROUP BY ?place_1 ?place_1_label ?number_2
LIMIT 10000
```

why not using `(GROUP_CONCAT(DISTINCT ?place_12_label; SEPARATOR = " ") AS ?place_12_label_group_concat)` ?

**Comment by ch-sander** [comment]
Maybe not a good idea, one can just concat the label directly as a property of the IRI

**Comment by tfrancart** [comment]
Yes, right now one could just apply the GROUP_CONCAT on the value of the label property in the query editor. But we could consider this as an improvement in the future.

**Comment by ch-sander** [comment]
It's fine, but requires a second thought if used by someone not familiar with the Graph
