### ISSUE TITLE
lang & defaultLang is required but all the data sources are not developed as multilingual

### ISSUE THREAD

**Issue by hashemirafsan** [sparna-git/Sparnatural#679]
I'm using react component of this. But recently i faced that in every query lang filter added but its not required all time. In my case, i haven't any requirement for lang validation. Is it possible to disable the lang filter? I'm adding screenshot for better understanding
<img width="1489" alt="Screenshot 2024-11-27 at 9 08 25 PM" src="https://github.com/user-attachments/assets/4b8b2fc5-ee87-431f-9567-8573481a0a36">

**Comment by tfrancart** [comment]
Yes, if you set the sh:datatype to xsd:string in your config, you shouldn't have any language filtering criteria. See https://docs.sparnatural.eu/how-to-configure-shacl/How-to-configure-Sparnatural-shacl.html#multilingual-default-label-properties

**Comment by tfrancart** [comment]
Closing this, feel free to reopen if your question wasn't answered
