### ISSUE TITLE
Issue with SHACL Path Expression Not Matching Expected SPARQL Property Path

### ISSUE THREAD

**Issue by ch-sander** [sparna-git/Sparnatural#688]
I'm encountering an issue with defining a SHACL path that corresponds to a specific SPARQL property path. My goal is to represent the following SPARQL property path in SHACL:

```
(grace:event_related_to_object | ^grace:object_related_to_event)*/(grace:object_related_to_object | ^grace:object_related_to_object)*
```

**Current SHACL Path Definitions:**

*In JSON-LD:*

```json
{
  "@list": [
    {
      "sh:zeroOrMorePath": {
        "sh:alternativePath": {
          "@list": [
            { "@id": "grace:event_related_to_object" },
            { "sh:inversePath": { "@id": "grace:object_related_to_event" } }
          ]
        }
      }
    },
    {
      "sh:zeroOrMorePath": {
        "sh:alternativePath": {
          "@list": [
            { "@id": "grace:object_related_to_object" },
            { "sh:inversePath": { "@id": "grace:object_related_to_object" } }
          ]
        }
      }
    }
  ]
}
```

*In Turtle notation:*

```turtle
sh:path (
  [
    sh:zeroOrMorePath [
      sh:alternativePath (
        grace:event_related_to_object
        [ sh:inversePath grace:object_related_to_event ]
      )
    ]
  ]
  [
    sh:zeroOrMorePath [
      sh:alternativePath (
        grace:object_related_to_object
        [ sh:inversePath grace:object_related_to_object ]
      )
    ]
  ]
) .
```

**Issue:**

Despite expecting the SHACL path to match the desired SPARQL property path, I am instead receiving the following SPARQL path when processing the SHACL definition in Sparnatural:

```
(grace:event_related_to_object | (^(grace:object_related_to_event*) / grace:object_related_to_object) | ^(grace:object_related_to_object*))
```

This path does not align with the intended property path. I suspect the issue might be due to how the SHACL path is structured or interpreted by the SHACL processor.

**Attempted Solution:**

I tried adjusting the SHACL path to explicitly define a sequence using `sh:sequence`:

```turtle
sh:path [
  sh:sequence (
    [
      sh:zeroOrMorePath [
        sh:alternativePath (
          grace:event_related_to_object
          [ sh:inversePath grace:object_related_to_event ]
        )
      ]
    ]
    [
      sh:zeroOrMorePath [
        sh:alternativePath (
          grace:object_related_to_object
          [ sh:inversePath grace:object_related_to_object ]
        )
      ]
    ]
  )
] .
```

However, this adjusted SHACL path is not accepted by the SHACL processor of Sparnatural.

**Goal:**

I aim to:

- Define a SHACL path that accurately represents the SPARQL property path:
  ```
  (grace:event_related_to_object | ^grace:object_related_to_event)*/(grace:object_related_to_object | ^grace:object_related_to_object)*
  ```
- Ensure that the SHACL path is correctly parsed and accepted by the SHACL processor.
- Understand why the current SHACL path is resulting in an incorrect SPARQL property path and how to adjust it properly.

Thank you!

**Comment by tfrancart** [comment]
Good catch ! your path expression is absolutely correct, the SPARQL translation was missing parenthesis around alternative paths.
