### ISSUE TITLE
Fail to Customize Classes

### ISSUE THREAD

**Issue by jingyuhhh** [sparna-git/Sparnatural#689]
I added two PREFIXes and two classes. However, I noticed that this Google Sheet failed to generate the expected entities.

Here is my Google Sheet: [link](https://docs.google.com/spreadsheets/d/1H74Fht79fOo-48tsspeejrOx-tJBg1I1mdHg31C73yA/edit?gid=468548378#gid=468548378). I’m not sure what went wrong.
![image](https://github.com/user-attachments/assets/904fa198-165d-4d1e-8880-03837df62958)

**Comment by tfrancart** [comment]
Please use a SHACL-based configuration. First read https://docs.sparnatural.eu/hello-sparnatural/Hello-Sparnatural.html, then https://docs.sparnatural.eu/how-to-configure-shacl/How-to-configure-Sparnatural-shacl.html. The spreadsheet template is different. Configuration is explained step by step.

**Comment by tfrancart** [comment]
Closing this, feel free to reopen if your question was not answered
