### ISSUE TITLE
Design interface

### ISSUE THREAD

**Issue by antoine37120** [sparna-git/Sparnatural#7]

**Comment by tfrancart** [comment]
Pour les icônes, pourrez-vous bien vous assurer de retravailler à partir des icônes qui étaient le powerpoint que j'avais envoyé ? car ils avaient été validé avec le client. Il faut les rendre plus jolis et homogènes, mais ne pas essayer de réinventer d'autres icônes !
Merci

**Comment by tfrancart** [comment]
![us](https://user-images.githubusercontent.com/2728945/48932978-bf192480-eefe-11e8-9f27-ebc74ebff427.png)
![icon_dig_hole_original](https://user-images.githubusercontent.com/2728945/48932986-c8a28c80-eefe-11e8-8a65-ed6a3af71a00.png)
![icon_cerceuil](https://user-images.githubusercontent.com/2728945/48932992-d0fac780-eefe-11e8-987f-602c9f10dc07.png)
![icon_wall_2](https://user-images.githubusercontent.com/2728945/48933004-db1cc600-eefe-11e8-9569-0751af91e27c.png)
![pottery-512](https://user-images.githubusercontent.com/2728945/48933012-e07a1080-eefe-11e8-8bb1-f0cfbd1b9c6e.png)
![icon-actor](https://user-images.githubusercontent.com/2728945/48933025-f1c31d00-eefe-11e8-803f-fc122315ae9e.png)
![icone_sablier](https://user-images.githubusercontent.com/2728945/48933037-fc7db200-eefe-11e8-93e5-7438254381a2.jpg)
![icon_places](https://user-images.githubusercontent.com/2728945/48933091-45ce0180-eeff-11e8-9757-6b58fd3919f3.png)
![drop_down_list](https://user-images.githubusercontent.com/2728945/48933097-4f576980-eeff-11e8-9d67-dfd3a55f7ea8.png)
![icon-text-search](https://user-images.githubusercontent.com/2728945/48933103-55e5e100-eeff-11e8-8cb4-a6d85927e53b.png)
![icon-site](https://user-images.githubusercontent.com/2728945/48933112-61d1a300-eeff-11e8-83a5-7c34a7f43bdf.png)

**Comment by tfrancart** [comment]
Merci aussi de prévoir que le composant doit marcher _même sans icônes_ paramétrés sur les classes

**Comment by antoine37120** [comment]
Suite à la première version de la maquettes : 
- Colorer le premier élément sélectionné
- Oublier la notion de requête terminée et la couleur rouge
- Ajouter une maquette pour le cas ou l'on a sélectionné une valeur
- Dans le cas ou une valeur est sélectionnée, colorer la valeur et non plus son type.
- Prévoir le survol pour l'activation des actions and ou or : Le And en dessous du premier objet de la ligne, le OR à l'horizontale après la dernière valeur sélectionnée.
