### ISSUE TITLE
Idée : ne pas avoir de wiget de sélection pour certains types (seulement des relations)

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#75]
Je me demande s'il n'y aurait pas des situations où on ne veut pas pouvoir sélectionner de valeur pour une entité, mais seulement naviguer dedans via un WHERE. Ce serait le cas d'entités "intermédiaires" qui n'ont de sens que pour naviguer dans d'autres entités, mais qu'on ne peut pas sélectionner.

On pourrait imaginer un type de widget "http://ontologies.sparna.fr/SimSemSearch#NoWidget" pour cela. Il ne faudrait présenter que le WHERE dans ce cas.

Pour l'instant c'est juste une idée ! pas besoin pour OpenArchaeo.

**Comment by tfrancart** [comment]
Valeur de type : `NonSelectableProperty`

**Comment by antoine37120** [comment]
@tfrancart Le widget est en place, tu peux le tester avec la relation Musé => Oeuvre

**Comment by tfrancart** [comment]
OK tested
