### ISSUE TITLE
Avoir un widget "URI simple"

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#76]
Nouveau type de widget ultra-basique : on saisie manuellement la valeur d'une URI, et elle est insérée telle quelle dans la requête SPARQL.
Ca permettrait de créer des requêtes SPARQL sans se préoccuper (dans un premier temps) de l'intégration avec de l'autocompletion ou des listes.

Valeur de widget dans la spec : `http://ontologies.sparna.fr/SimSemSearch#BasicURIWidget`

**Comment by antoine37120** [comment]
A priori, il suffirait de dupliquer le code du widget "SearchWidget" et ajouter un traitement dédié à ce widget dans QueryGenerators.js dans le switch ligne 182.
