### ISSUE TITLE
Problèmes d'affichage

### ISSUE THREAD

**Issue by BenjaminQuidelleur** [sparna-git/Sparnatural#85]
Bonjour,
Jj'ai un problème d'affichage lorsque j'accède à index.html avec un serveur nginx.
Les fichiers simsearch-min.css n'est pas présent ainsi que les dossiers d'icon noir et blanc .Je n'arrive donc pas à construire de requêtes. 

Il y a-t-il un moyen de résoudre ce problème ?

**Comment by tfrancart** [comment]
Merci, j'ai déplacé la démo dans un sous-répertoire à part, mis à jour le fichier index.html et inclut les icônes, ça devrait le faire. Regardez plutôt l'autre démo dbpedia dans le sous-répertoire `sparnatural-demo-dbpedia`, elle illustre mieux l'intégration avec un endpoint SPARQL.

**Comment by BenjaminQuidelleur** [comment]
Merci, j'ai essayé avec la démo dbpedia mais j'essaie de configurer pour utiliser sparnatural avec un endpoint personnel. 
Est-ce possible de générer le fichier de config JSON LD avec un fichier d'ontologie au format ttl ?

**Comment by tfrancart** [comment]
> Merci, j'ai essayé avec la démo dbpedia mais j'essaie de configurer pour utiliser sparnatural avec un endpoint personnel.

Donc la démo DBPedia est le bon point de départ. Changez l'URL du SPARQL endpoint dans le source de la démo.
Attention votre endpoint personnel, s'il est sur un serveur en ligne, doit accepter les requêtes CORS, sinon vous aurez des exceptions de sécurité.

> Est-ce possible de générer le fichier de config JSON LD avec un fichier d'ontologie au format ttl ?

Non, actuellement même si le fichier est un JSON-LD valable le parsing de la config se fait bien au niveau JSON. La seule solution est d'éditer la config à la main. Le parsing de la spec en RDF fait partie des idées d'évolution.

Si vous avez d'autres soucis n'hésitez pas à ouvrir d'autres tickets, si la correction de celui-ci vous semble effective (si ce n'est pas le cas rouvrez le ticket).

**Comment by BenjaminQuidelleur** [comment]
Bonjour, j'ai essayé de modifier le fichier spec-search-dbpedia pour l'adapter à mon endpoint. Quand vous dites d'éditer la config à la main vous parlez de ce fichier ou bien il faut aussi modifier le fichier sparnatural-min.js ?

**Comment by tfrancart** [comment]
Non il s’agit uniquement du fichier de spec. Il n’est pas nécessaire de faire de modif dans le js, sauf si vous voulez faire évoluer le composant. 

Thomas

Envoyé de mon iPhone
