### ISSUE TITLE
Widget auto-completion

### ISSUE THREAD

**Issue by antoine37120** [sparna-git/Sparnatural#9]

**Comment by tfrancart** [comment]
Pour la spécification des URLs à appeler des widgets, il faut mieux prendre en paramètre du module une fonction de callback :

new SimSemSearchForm(
  autocomplete: new function(domain, property, range, key) {
    // ici le code qui se charge de retourner les résultats de la recherche
  }
)

ainsi :
  - plus la peine de mettre les URLs dans la spécification JSON
  - on ne hardcode rien dans le code

qu'en penses-tu ? on en parle de vive voix si ce n'est pas clair

**Comment by tfrancart** [comment]
1. Pour l'instant on externalise seulement l'URL d'appel d'autocompletion dans le callback
2. Dans un deuxième temps il faudra ajouter un paramètre dans la spec pour indiquer si pour un champ on veut charger toutes les valeurs ou si c'est l'URL qui se charge de la recherche (option "match" de easyautocomplete)

**Comment by tfrancart** [comment]
Antoine, il faut ajouter le paramètre de langue à la signature de la méthode d'autocomplete :

new SimSemSearchForm(
  autocomplete: new function(domain, property, range, key, **lang**) {
    ...
  }
)

Merci
