### ISSUE TITLE
Widget de sélection de date simple, sans le champ de recherche/sélection dans les périodes

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#90]
Indiquer seulement année de début et année de fin

**Comment by antoine37120** [comment]
Pourvoir sélectionner une seule date (début ou fin)

**Comment by antoine37120** [comment]
@tfrancart, le fonctionnement du widget et la génération de la requête fonctionnent. Il est possible de préciser qu'une seule date.
Petit changement de logique de l'opérateur du filtre pour la date de début. L'opérateur était ">". Je l'ai remplacé par ">=". Cela parait plus cohérent avec l'idée que l'on se fait en lisant l'interface. et nous avion le même type d'opérateur pour la date de fin ">=". Cela signifie donc que si on sélectionne une année pour le début de la période, le 1er janvier ne sera plus excluant.

**Comment by antoine37120** [comment]
Pour ce widget, il ne reste plus qu'a traiter les traductions et le soucis global lié à l'affichage seulement au survol des critères.
J'oubliais, n'oublis pas de porter une petite attention à l'affichage des dates un fois la sélection validée dans les cas ou une seul date est renseignée. Nous ne pouvons plus dire "De xxxx à xxxx".

**Comment by tfrancart** [comment]
Petit commentaire : comme pour les autres critères de type "Musée expose Oeuvre", quand je fais "Personne date de décès Date", on pourrait s'attendre à ce que la requête soit générée, sans le critère de valeur, pour sélectionner toutes les personnes dont la date de décès est connue.

**Comment by tfrancart** [comment]
1. **Bloquant : Quand le format est TimeDatePickerProperty, le placeholder devrait montrer "AAAA", sinon ce n'est pas clair.**
2. Je vois que "fr-FR" est passé en dur au constructeur du date picker, c'est normal ?
3. En anglais le format devrait être "dd-mm-yyyy" (mettre les y en minuscule). Et en français mettre le AAAA en minuscules : aaaa

**Comment by antoine37120** [comment]
Salut @tfrancart, je viens de faire les corrections et ajouts pour les formats de date dans les fichiers de langue. Lignes 11 à 15.
Pour ce qui commence par "Input", il s'agit des formats normés attendu pour la config du datepicker.
Ceux qui commencent par "Placehoder" concernent ce qui est visible pour l’utilisateur dans le champ de la date.
Le langage du datepicker est configuré avec "LangCodeTimeDate".

**Comment by tfrancart** [comment]
OK
