### ISSUE TITLE
Permettre une sélection de valeur litérales dans une liste

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#91]
Cas d'usage : foaf:gender, fieldOfActivityOfThePerson dans data.bnf.
Dans ce cas la valeur choisie est un litéral directement, pas une URI.

**Comment by tfrancart** [comment]
Pour le dire autrement : on veut un widget de sélection dans une liste de valeur (comme le widget existant actuel), mais les valeurs ne sont pas des URIs d'objet mais des chaines de caractères. La requête SPARQL générée change.

Par exemple, avec le widget existant, quand je sélectionne "toutes les oeuvres de Léonard de Vinci", ça génère :

```
SELECT DISTINCT ?this WHERE {
  ?this <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Artwork>;
    <http://dbpedia.org/ontology/author> <http://fr.dbpedia.org/resource/Léonard_de_Vinci>.
}
```

Mais si l'auteur de l'ouevre était une chaine de caractères et pas un identifiant, on devrait générer :


```
SELECT DISTINCT ?this WHERE {
  ?this <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Artwork>;
    <http://dbpedia.org/ontology/author> "Léonard de Vinci".
}
```

ou, quand il y a plusieurs valeurs :

```
SELECT DISTINCT ?this WHERE {
  ?this <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Artwork>;
    <http://dbpedia.org/ontology/author> ?auteur.
  VALUES ?auteur { "Léonar de Vinci", "Michel Ange" }
}
```

Attention ça doit aussi changer la façon de récupérer les valeurs pour alimenter la liste ? à voir

**Comment by antoine37120** [comment]
Pour le traitement lors de la génération de la requête, il est possible de reconnaître le type de valeur et mettre en place une implémentation pour les 2 cas de figure. (pour les uri, il y aura toujours un http au début de la valeur ?).
Pour le widget, peut être est-ce plus simple de continuer à récupérer les valeurs avec la fonction "elementUri()". Par défaut, elle retourne la propriété uri de l'élément à lister mais cela est personnalisable lors de la configuration du composant.
Peut être que le nom de cette fonction n'est plus cohérent avec les différents cas de figure. Peut être la renommer "elementValue()". Le concept général des listes déroulantes est qu'il y a des valeurs affichées (les labels) et des valeurs associées pour le traitement de la sélection (Value).

**Comment by tfrancart** [comment]
J'ai fait des évolutions pour supporter ce cas d'usage - ca marche, mais il faut encore:

- etre capable de récupérer la lang et le datatype du literal dans la valeur pour la repasser dans la requête SPARQL. Pour le moment seules les chaines de caractères simples fonctionnent comme valeur
- renommer elementUri en elementValue
- documenter que la requête peut ramener une variable "value" à la place de "uri"
- générer un peu différemment le triplet de sortie dans buildTriple() pour bien mettre la lang et le datatype
