### ISSUE TITLE
Widget "aucun widget" qui permettrait de simplement tester la présence de la propriété sans pouvoir sélectionner de valeur

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#92]
"Je veux toutes les éditions d'une oeuvre qui ont une reproduction électronique"

**Comment by tfrancart** [comment]
(Utile si on veut faire de la sélection de valeurs dans le pattern de query)

**Comment by antoine37120** [comment]
Je pense que ce devrait être une option incluse dans chaque type de widget lorsqu'il s'agit de sélectionner une valeur pour un critère (option possible seulement quand aucune valeur n'est déjà sélectionnée.
Ce pourrait être une case à cocher "Non vide"/"Not null" qui permettrait de valider le formulaire d'ajout de valeur pour l'utilisateur.

**Comment by tfrancart** [comment]
Non, c'est trop compliqué pour l'utilisateur, et ce n'est pas le même usage. Il faut vraiment un widget différent qui interdit à la fois la sélection d'une valeur et l'action de descendre dans un WHERE

**Comment by tfrancart** [comment]
Actually, this already works. BUT we need to avoid inserting the rdf:type criteria in the corresponding query

**Comment by tfrancart** [comment]
Introduced Literal class
