### ISSUE TITLE
Permettre de customiser la génération des filtres plein-texte

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/Sparnatural#93]
Aujourd'hui, on génère un `FILTER(CONTAINS(...))`, mais parfois on voudrait générer un `bif:contains`ou un prédicat magique GraphDB.

**Comment by tfrancart** [comment]
Nécessite un refactoring des widgets sous forme de classe

**Comment by antoine37120** [comment]
Il faudra que tu m'explique de vive voix.

**Comment by tfrancart** [comment]
Adressed by the datasource configuration.
Duplicates #149
